use super::*;
use std::cell::{Cell, RefCell};
use std::collections::VecDeque;
use std::ptr::null_mut;
use std::sync::atomic::{AtomicPtr, Ordering};

// #3677: `Object.keys(zlib.constants)` enumeration. Node exposes the full
// Z_*/BROTLI_*/ZSTD_* table as enumerable own keys (170 keys). Every key here
// is backed by a value in `zlib_const` (the value-read dispatch), so
// enumeration and direct reads agree. Order matches Node's insertion order.
const ZLIB_CONSTANTS_KEYS: &[&[u8]] = &[
    b"Z_NO_FLUSH",
    b"Z_PARTIAL_FLUSH",
    b"Z_SYNC_FLUSH",
    b"Z_FULL_FLUSH",
    b"Z_FINISH",
    b"Z_BLOCK",
    b"Z_OK",
    b"Z_STREAM_END",
    b"Z_NEED_DICT",
    b"Z_ERRNO",
    b"Z_STREAM_ERROR",
    b"Z_DATA_ERROR",
    b"Z_MEM_ERROR",
    b"Z_BUF_ERROR",
    b"Z_VERSION_ERROR",
    b"Z_NO_COMPRESSION",
    b"Z_BEST_SPEED",
    b"Z_BEST_COMPRESSION",
    b"Z_DEFAULT_COMPRESSION",
    b"Z_FILTERED",
    b"Z_HUFFMAN_ONLY",
    b"Z_RLE",
    b"Z_FIXED",
    b"Z_DEFAULT_STRATEGY",
    b"ZLIB_VERNUM",
    b"DEFLATE",
    b"INFLATE",
    b"GZIP",
    b"GUNZIP",
    b"DEFLATERAW",
    b"INFLATERAW",
    b"UNZIP",
    b"BROTLI_DECODE",
    b"BROTLI_ENCODE",
    b"ZSTD_DECOMPRESS",
    b"ZSTD_COMPRESS",
    b"Z_MIN_WINDOWBITS",
    b"Z_MAX_WINDOWBITS",
    b"Z_DEFAULT_WINDOWBITS",
    b"Z_MIN_CHUNK",
    b"Z_MAX_CHUNK",
    b"Z_DEFAULT_CHUNK",
    b"Z_MIN_MEMLEVEL",
    b"Z_MAX_MEMLEVEL",
    b"Z_DEFAULT_MEMLEVEL",
    b"Z_MIN_LEVEL",
    b"Z_MAX_LEVEL",
    b"Z_DEFAULT_LEVEL",
    b"BROTLI_OPERATION_PROCESS",
    b"BROTLI_OPERATION_FLUSH",
    b"BROTLI_OPERATION_FINISH",
    b"BROTLI_OPERATION_EMIT_METADATA",
    b"BROTLI_PARAM_MODE",
    b"BROTLI_MODE_GENERIC",
    b"BROTLI_MODE_TEXT",
    b"BROTLI_MODE_FONT",
    b"BROTLI_DEFAULT_MODE",
    b"BROTLI_PARAM_QUALITY",
    b"BROTLI_MIN_QUALITY",
    b"BROTLI_MAX_QUALITY",
    b"BROTLI_DEFAULT_QUALITY",
    b"BROTLI_PARAM_LGWIN",
    b"BROTLI_MIN_WINDOW_BITS",
    b"BROTLI_MAX_WINDOW_BITS",
    b"BROTLI_LARGE_MAX_WINDOW_BITS",
    b"BROTLI_DEFAULT_WINDOW",
    b"BROTLI_PARAM_LGBLOCK",
    b"BROTLI_MIN_INPUT_BLOCK_BITS",
    b"BROTLI_MAX_INPUT_BLOCK_BITS",
    b"BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING",
    b"BROTLI_PARAM_SIZE_HINT",
    b"BROTLI_PARAM_LARGE_WINDOW",
    b"BROTLI_PARAM_NPOSTFIX",
    b"BROTLI_PARAM_NDIRECT",
    b"BROTLI_DECODER_RESULT_ERROR",
    b"BROTLI_DECODER_RESULT_SUCCESS",
    b"BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT",
    b"BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT",
    b"BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION",
    b"BROTLI_DECODER_PARAM_LARGE_WINDOW",
    b"BROTLI_DECODER_NO_ERROR",
    b"BROTLI_DECODER_SUCCESS",
    b"BROTLI_DECODER_NEEDS_MORE_INPUT",
    b"BROTLI_DECODER_NEEDS_MORE_OUTPUT",
    b"BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE",
    b"BROTLI_DECODER_ERROR_FORMAT_RESERVED",
    b"BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE",
    b"BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET",
    b"BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME",
    b"BROTLI_DECODER_ERROR_FORMAT_CL_SPACE",
    b"BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE",
    b"BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT",
    b"BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1",
    b"BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2",
    b"BROTLI_DECODER_ERROR_FORMAT_TRANSFORM",
    b"BROTLI_DECODER_ERROR_FORMAT_DICTIONARY",
    b"BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS",
    b"BROTLI_DECODER_ERROR_FORMAT_PADDING_1",
    b"BROTLI_DECODER_ERROR_FORMAT_PADDING_2",
    b"BROTLI_DECODER_ERROR_FORMAT_DISTANCE",
    b"BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET",
    b"BROTLI_DECODER_ERROR_INVALID_ARGUMENTS",
    b"BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES",
    b"BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS",
    b"BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP",
    b"BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1",
    b"BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2",
    b"BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES",
    b"BROTLI_DECODER_ERROR_UNREACHABLE",
    b"ZSTD_e_continue",
    b"ZSTD_e_flush",
    b"ZSTD_e_end",
    b"ZSTD_fast",
    b"ZSTD_dfast",
    b"ZSTD_greedy",
    b"ZSTD_lazy",
    b"ZSTD_lazy2",
    b"ZSTD_btlazy2",
    b"ZSTD_btopt",
    b"ZSTD_btultra",
    b"ZSTD_btultra2",
    b"ZSTD_c_compressionLevel",
    b"ZSTD_c_windowLog",
    b"ZSTD_c_hashLog",
    b"ZSTD_c_chainLog",
    b"ZSTD_c_searchLog",
    b"ZSTD_c_minMatch",
    b"ZSTD_c_targetLength",
    b"ZSTD_c_strategy",
    b"ZSTD_c_enableLongDistanceMatching",
    b"ZSTD_c_ldmHashLog",
    b"ZSTD_c_ldmMinMatch",
    b"ZSTD_c_ldmBucketSizeLog",
    b"ZSTD_c_ldmHashRateLog",
    b"ZSTD_c_contentSizeFlag",
    b"ZSTD_c_checksumFlag",
    b"ZSTD_c_dictIDFlag",
    b"ZSTD_c_nbWorkers",
    b"ZSTD_c_jobSize",
    b"ZSTD_c_overlapLog",
    b"ZSTD_d_windowLogMax",
    b"ZSTD_CLEVEL_DEFAULT",
    b"ZSTD_error_no_error",
    b"ZSTD_error_GENERIC",
    b"ZSTD_error_prefix_unknown",
    b"ZSTD_error_version_unsupported",
    b"ZSTD_error_frameParameter_unsupported",
    b"ZSTD_error_frameParameter_windowTooLarge",
    b"ZSTD_error_corruption_detected",
    b"ZSTD_error_checksum_wrong",
    b"ZSTD_error_literals_headerWrong",
    b"ZSTD_error_dictionary_corrupted",
    b"ZSTD_error_dictionary_wrong",
    b"ZSTD_error_dictionaryCreation_failed",
    b"ZSTD_error_parameter_unsupported",
    b"ZSTD_error_parameter_combination_unsupported",
    b"ZSTD_error_parameter_outOfBound",
    b"ZSTD_error_tableLog_tooLarge",
    b"ZSTD_error_maxSymbolValue_tooLarge",
    b"ZSTD_error_maxSymbolValue_tooSmall",
    b"ZSTD_error_stabilityCondition_notRespected",
    b"ZSTD_error_stage_wrong",
    b"ZSTD_error_init_missing",
    b"ZSTD_error_memory_allocation",
    b"ZSTD_error_workSpace_tooSmall",
    b"ZSTD_error_dstSize_tooSmall",
    b"ZSTD_error_srcSize_wrong",
    b"ZSTD_error_dstBuffer_null",
    b"ZSTD_error_noForwardProgress_destFull",
    b"ZSTD_error_noForwardProgress_inputEmpty",
];

const DEPRECATED_CONSTANTS_KEYS: &[&[u8]] = &[
    b"F_OK",
    b"R_OK",
    b"W_OK",
    b"X_OK",
    b"O_RDONLY",
    b"O_WRONLY",
    b"O_RDWR",
    b"O_NOFOLLOW",
    b"O_CREAT",
    b"O_TRUNC",
    b"O_APPEND",
    b"O_EXCL",
    b"COPYFILE_EXCL",
    b"COPYFILE_FICLONE",
    b"COPYFILE_FICLONE_FORCE",
    b"S_IRUSR",
    b"S_IWUSR",
    b"S_IXUSR",
    b"S_IRGRP",
    b"S_IWGRP",
    b"S_IXGRP",
    b"S_IROTH",
    b"S_IWOTH",
    b"S_IXOTH",
    b"SIGHUP",
    b"SIGINT",
    b"SIGQUIT",
    b"SIGILL",
    b"SIGTRAP",
    b"SIGABRT",
    b"SIGIOT",
    b"SIGBUS",
    b"SIGFPE",
    b"SIGKILL",
    b"SIGUSR1",
    b"SIGSEGV",
    b"SIGUSR2",
    b"SIGPIPE",
    b"SIGALRM",
    b"SIGTERM",
    b"SIGCHLD",
    b"SIGCONT",
    b"SIGSTOP",
    b"SIGTSTP",
    b"SIGTTIN",
    b"SIGTTOU",
    b"SIGURG",
    b"SIGXCPU",
    b"SIGXFSZ",
    b"SIGVTALRM",
    b"SIGPROF",
    b"SIGWINCH",
    b"SIGIO",
    b"SIGSYS",
    b"E2BIG",
    b"EACCES",
    b"EADDRINUSE",
    b"EADDRNOTAVAIL",
    b"EAFNOSUPPORT",
    b"EAGAIN",
    b"EALREADY",
    b"EBADF",
    b"EBADMSG",
    b"EBUSY",
    b"ECANCELED",
    b"ECHILD",
    b"ECONNABORTED",
    b"ECONNREFUSED",
    b"ECONNRESET",
    b"EDEADLK",
    b"EDESTADDRREQ",
    b"EDOM",
    b"EDQUOT",
    b"EEXIST",
    b"EFAULT",
    b"EFBIG",
    b"EHOSTUNREACH",
    b"EIDRM",
    b"EILSEQ",
    b"EINPROGRESS",
    b"EINTR",
    b"EINVAL",
    b"EIO",
    b"EISCONN",
    b"EISDIR",
    b"ELOOP",
    b"EMFILE",
    b"EMLINK",
    b"EMSGSIZE",
    b"EMULTIHOP",
    b"ENAMETOOLONG",
    b"ENETDOWN",
    b"ENETRESET",
    b"ENETUNREACH",
    b"ENFILE",
    b"ENOBUFS",
    b"ENODATA",
    b"ENODEV",
    b"ENOENT",
    b"ENOEXEC",
    b"ENOLCK",
    b"ENOLINK",
    b"ENOMEM",
    b"ENOMSG",
    b"ENOPROTOOPT",
    b"ENOSPC",
    b"ENOSR",
    b"ENOSTR",
    b"ENOSYS",
    b"ENOTCONN",
    b"ENOTDIR",
    b"ENOTEMPTY",
    b"ENOTSOCK",
    b"ENOTSUP",
    b"ENOTTY",
    b"ENXIO",
    b"EOPNOTSUPP",
    b"EOVERFLOW",
    b"EPERM",
    b"EPIPE",
    b"EPROTO",
    b"EPROTONOSUPPORT",
    b"EPROTOTYPE",
    b"ERANGE",
    b"EROFS",
    b"ESPIPE",
    b"ESRCH",
    b"ESTALE",
    b"ETIME",
    b"ETIMEDOUT",
    b"ETXTBSY",
    b"EWOULDBLOCK",
    b"EXDEV",
    b"PRIORITY_LOW",
    b"PRIORITY_BELOW_NORMAL",
    b"PRIORITY_NORMAL",
    b"PRIORITY_ABOVE_NORMAL",
    b"PRIORITY_HIGH",
    b"PRIORITY_HIGHEST",
    b"RTLD_LAZY",
    b"RTLD_NOW",
    b"RTLD_GLOBAL",
    b"RTLD_LOCAL",
    b"OPENSSL_VERSION_NUMBER",
    b"SSL_OP_ALL",
    b"SSL_OP_ALLOW_NO_DHE_KEX",
    b"SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION",
    b"SSL_OP_CIPHER_SERVER_PREFERENCE",
    b"SSL_OP_CISCO_ANYCONNECT",
    b"SSL_OP_COOKIE_EXCHANGE",
    b"SSL_OP_CRYPTOPRO_TLSEXT_BUG",
    b"SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS",
    b"SSL_OP_LEGACY_SERVER_CONNECT",
    b"SSL_OP_NO_COMPRESSION",
    b"SSL_OP_NO_ENCRYPT_THEN_MAC",
    b"SSL_OP_NO_QUERY_MTU",
    b"SSL_OP_NO_RENEGOTIATION",
    b"SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION",
    b"SSL_OP_NO_SSLv2",
    b"SSL_OP_NO_SSLv3",
    b"SSL_OP_NO_TICKET",
    b"SSL_OP_NO_TLSv1",
    b"SSL_OP_NO_TLSv1_1",
    b"SSL_OP_NO_TLSv1_2",
    b"SSL_OP_NO_TLSv1_3",
    b"SSL_OP_PRIORITIZE_CHACHA",
    b"SSL_OP_TLS_ROLLBACK_BUG",
    b"ENGINE_METHOD_RSA",
    b"ENGINE_METHOD_DSA",
    b"ENGINE_METHOD_DH",
    b"ENGINE_METHOD_RAND",
    b"ENGINE_METHOD_EC",
    b"ENGINE_METHOD_CIPHERS",
    b"ENGINE_METHOD_DIGESTS",
    b"ENGINE_METHOD_PKEY_METHS",
    b"ENGINE_METHOD_PKEY_ASN1_METHS",
    b"ENGINE_METHOD_ALL",
    b"ENGINE_METHOD_NONE",
    b"DH_CHECK_P_NOT_SAFE_PRIME",
    b"DH_CHECK_P_NOT_PRIME",
    b"DH_UNABLE_TO_CHECK_GENERATOR",
    b"DH_NOT_SUITABLE_GENERATOR",
    b"RSA_PKCS1_PADDING",
    b"RSA_NO_PADDING",
    b"RSA_PKCS1_OAEP_PADDING",
    b"RSA_X931_PADDING",
    b"RSA_PKCS1_PSS_PADDING",
    b"RSA_PSS_SALTLEN_DIGEST",
    b"RSA_PSS_SALTLEN_MAX_SIGN",
    b"RSA_PSS_SALTLEN_AUTO",
    b"TLS1_VERSION",
    b"TLS1_1_VERSION",
    b"TLS1_2_VERSION",
    b"TLS1_3_VERSION",
    b"POINT_CONVERSION_COMPRESSED",
    b"POINT_CONVERSION_UNCOMPRESSED",
    b"POINT_CONVERSION_HYBRID",
    // #3683: POSIX file-flag, libuv, and default-cipher-metadata tail.
    b"UV_DIRENT_UNKNOWN",
    b"UV_DIRENT_FILE",
    b"UV_DIRENT_DIR",
    b"UV_DIRENT_LINK",
    b"UV_DIRENT_FIFO",
    b"UV_DIRENT_SOCKET",
    b"UV_DIRENT_CHAR",
    b"UV_DIRENT_BLOCK",
    b"UV_FS_SYMLINK_DIR",
    b"UV_FS_SYMLINK_JUNCTION",
    b"UV_FS_O_FILEMAP",
    b"UV_FS_COPYFILE_EXCL",
    b"UV_FS_COPYFILE_FICLONE",
    b"UV_FS_COPYFILE_FICLONE_FORCE",
    b"S_IFMT",
    b"S_IFREG",
    b"S_IFDIR",
    b"S_IFCHR",
    b"S_IFBLK",
    b"S_IFIFO",
    b"S_IFLNK",
    b"S_IFSOCK",
    b"S_IRWXU",
    b"S_IRWXG",
    b"S_IRWXO",
    b"O_DIRECTORY",
    b"O_NOCTTY",
    b"O_NONBLOCK",
    b"O_SYNC",
    b"O_DSYNC",
    b"defaultCoreCipherList",
];

const ASYNC_HOOKS_DEFAULT_KEYS: &[&[u8]] = &[
    b"AsyncLocalStorage",
    b"createHook",
    b"executionAsyncId",
    b"triggerAsyncId",
    b"executionAsyncResource",
    b"asyncWrapProviders",
    b"AsyncResource",
];

const ASYNC_HOOKS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"AsyncLocalStorage",
    b"AsyncResource",
    b"asyncWrapProviders",
    b"createHook",
    b"default",
    b"executionAsyncId",
    b"executionAsyncResource",
    b"triggerAsyncId",
];

const STREAM_NAMESPACE_KEYS: &[&[u8]] = &[
    b"Duplex",
    b"PassThrough",
    b"Readable",
    b"Stream",
    b"Transform",
    b"Writable",
    b"_isArrayBufferView",
    b"_isUint8Array",
    b"_uint8ArrayToBuffer",
    b"addAbortSignal",
    b"compose",
    b"default",
    b"duplexPair",
    b"finished",
    b"getDefaultHighWaterMark",
    b"isDestroyed",
    b"isDisturbed",
    b"isErrored",
    b"isReadable",
    b"isWritable",
    b"pipeline",
    b"promises",
    b"setDefaultHighWaterMark",
];

const DNS_DEFAULT_KEYS: &[&[u8]] = &[
    b"lookup",
    b"lookupService",
    b"Resolver",
    b"getDefaultResultOrder",
    b"setDefaultResultOrder",
    b"setServers",
    b"ADDRCONFIG",
    b"ALL",
    b"V4MAPPED",
    b"NODATA",
    b"FORMERR",
    b"SERVFAIL",
    b"NOTFOUND",
    b"NOTIMP",
    b"REFUSED",
    b"BADQUERY",
    b"BADNAME",
    b"BADFAMILY",
    b"BADRESP",
    b"CONNREFUSED",
    b"TIMEOUT",
    b"EOF",
    b"FILE",
    b"NOMEM",
    b"DESTRUCTION",
    b"BADSTR",
    b"BADFLAGS",
    b"NONAME",
    b"BADHINTS",
    b"NOTINITIALIZED",
    b"LOADIPHLPAPI",
    b"ADDRGETNETWORKPARAMS",
    b"CANCELLED",
    b"getServers",
    b"resolve",
    b"resolve4",
    b"resolve6",
    b"resolveAny",
    b"resolveCaa",
    b"resolveCname",
    b"resolveMx",
    b"resolveNaptr",
    b"resolveNs",
    b"resolvePtr",
    b"resolveSoa",
    b"resolveSrv",
    b"resolveTlsa",
    b"resolveTxt",
    b"reverse",
    b"promises",
];

const DNS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"ADDRCONFIG",
    b"ADDRGETNETWORKPARAMS",
    b"ALL",
    b"BADFAMILY",
    b"BADFLAGS",
    b"BADHINTS",
    b"BADNAME",
    b"BADQUERY",
    b"BADRESP",
    b"BADSTR",
    b"CANCELLED",
    b"CONNREFUSED",
    b"DESTRUCTION",
    b"EOF",
    b"FILE",
    b"FORMERR",
    b"LOADIPHLPAPI",
    b"NODATA",
    b"NOMEM",
    b"NONAME",
    b"NOTFOUND",
    b"NOTIMP",
    b"NOTINITIALIZED",
    b"REFUSED",
    b"Resolver",
    b"SERVFAIL",
    b"TIMEOUT",
    b"V4MAPPED",
    b"default",
    b"getDefaultResultOrder",
    b"getServers",
    b"lookup",
    b"lookupService",
    b"promises",
    b"resolve",
    b"resolve4",
    b"resolve6",
    b"resolveAny",
    b"resolveCaa",
    b"resolveCname",
    b"resolveMx",
    b"resolveNaptr",
    b"resolveNs",
    b"resolvePtr",
    b"resolveSoa",
    b"resolveSrv",
    b"resolveTlsa",
    b"resolveTxt",
    b"reverse",
    b"setDefaultResultOrder",
    b"setServers",
];

const DNS_PROMISES_DEFAULT_KEYS: &[&[u8]] = &[
    b"lookup",
    b"lookupService",
    b"Resolver",
    b"getDefaultResultOrder",
    b"setDefaultResultOrder",
    b"setServers",
    b"NODATA",
    b"FORMERR",
    b"SERVFAIL",
    b"NOTFOUND",
    b"NOTIMP",
    b"REFUSED",
    b"BADQUERY",
    b"BADNAME",
    b"BADFAMILY",
    b"BADRESP",
    b"CONNREFUSED",
    b"TIMEOUT",
    b"EOF",
    b"FILE",
    b"NOMEM",
    b"DESTRUCTION",
    b"BADSTR",
    b"BADFLAGS",
    b"NONAME",
    b"BADHINTS",
    b"NOTINITIALIZED",
    b"LOADIPHLPAPI",
    b"ADDRGETNETWORKPARAMS",
    b"CANCELLED",
    b"getServers",
    b"resolve",
    b"resolve4",
    b"resolve6",
    b"resolveAny",
    b"resolveCaa",
    b"resolveCname",
    b"resolveMx",
    b"resolveNaptr",
    b"resolveNs",
    b"resolvePtr",
    b"resolveSoa",
    b"resolveSrv",
    b"resolveTlsa",
    b"resolveTxt",
    b"reverse",
];

const DNS_PROMISES_NAMESPACE_KEYS: &[&[u8]] = &[
    b"ADDRGETNETWORKPARAMS",
    b"BADFAMILY",
    b"BADFLAGS",
    b"BADHINTS",
    b"BADNAME",
    b"BADQUERY",
    b"BADRESP",
    b"BADSTR",
    b"CANCELLED",
    b"CONNREFUSED",
    b"DESTRUCTION",
    b"EOF",
    b"FILE",
    b"FORMERR",
    b"LOADIPHLPAPI",
    b"NODATA",
    b"NOMEM",
    b"NONAME",
    b"NOTFOUND",
    b"NOTIMP",
    b"NOTINITIALIZED",
    b"REFUSED",
    b"Resolver",
    b"SERVFAIL",
    b"TIMEOUT",
    b"default",
    b"getDefaultResultOrder",
    b"getServers",
    b"lookup",
    b"lookupService",
    b"resolve",
    b"resolve4",
    b"resolve6",
    b"resolveAny",
    b"resolveCaa",
    b"resolveCname",
    b"resolveMx",
    b"resolveNaptr",
    b"resolveNs",
    b"resolvePtr",
    b"resolveSoa",
    b"resolveSrv",
    b"resolveTlsa",
    b"resolveTxt",
    b"reverse",
    b"setDefaultResultOrder",
    b"setServers",
];

const CHILD_PROCESS_DEFAULT_KEYS: &[&[u8]] = &[
    b"ChildProcess",
    b"_forkChild",
    b"exec",
    b"execFile",
    b"execFileSync",
    b"execSync",
    b"fork",
    b"spawn",
    b"spawnSync",
];

const CHILD_PROCESS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"ChildProcess",
    b"_forkChild",
    b"default",
    b"exec",
    b"execFile",
    b"execFileSync",
    b"execSync",
    b"fork",
    b"spawn",
    b"spawnSync",
];

// #6563: node-pty / @lydell/node-pty — `spawn` is the entire module surface
// the target apps touch; everything else lives on the returned IPty object.
const NODE_PTY_DEFAULT_KEYS: &[&[u8]] = &[b"spawn"];

const NODE_PTY_NAMESPACE_KEYS: &[&[u8]] = &[b"default", b"spawn"];

const CLUSTER_NAMESPACE_KEYS: &[&[u8]] = &[
    b"SCHED_NONE",
    b"SCHED_RR",
    b"Worker",
    b"_events",
    b"_eventsCount",
    b"_maxListeners",
    b"default",
    b"disconnect",
    b"fork",
    b"isMaster",
    b"isPrimary",
    b"isWorker",
    b"schedulingPolicy",
    b"settings",
    b"setupMaster",
    b"setupPrimary",
    b"workers",
];

const CLUSTER_DEFAULT_KEYS: &[&[u8]] = &[
    b"_events",
    b"_eventsCount",
    b"_maxListeners",
    b"isWorker",
    b"isMaster",
    b"isPrimary",
    b"Worker",
    b"workers",
    b"settings",
    b"SCHED_NONE",
    b"SCHED_RR",
    b"schedulingPolicy",
    b"setupPrimary",
    b"setupMaster",
    b"fork",
    b"disconnect",
];

const PROCESS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"_debugEnd",
    b"_debugProcess",
    b"_events",
    b"_eventsCount",
    b"_exiting",
    b"_fatalException",
    b"_getActiveHandles",
    b"_getActiveRequests",
    b"_kill",
    b"_linkedBinding",
    b"_maxListeners",
    b"_preload_modules",
    b"_rawDebug",
    b"_startProfilerIdleNotifier",
    b"_stopProfilerIdleNotifier",
    b"_tickCallback",
    b"abort",
    b"addListener",
    b"addUncaughtExceptionCaptureCallback",
    b"allowedNodeEnvironmentFlags",
    b"argv",
    b"argv0",
    b"arch",
    b"binding",
    b"channel",
    b"chdir",
    b"config",
    b"connected",
    b"cpuUsage",
    b"cwd",
    b"debugPort",
    b"default",
    b"disconnect",
    b"dlopen",
    b"domain",
    b"env",
    b"eventNames",
    b"execve",
    b"execArgv",
    b"execPath",
    b"features",
    b"finalization",
    b"getActiveResourcesInfo",
    b"getBuiltinModule",
    b"getMaxListeners",
    b"hrtime",
    b"kill",
    b"listenerCount",
    b"listeners",
    b"memoryUsage",
    b"moduleLoadList",
    b"nextTick",
    b"off",
    b"on",
    b"once",
    b"openStdin",
    b"pid",
    b"platform",
    b"ppid",
    b"prependListener",
    b"prependOnceListener",
    b"rawListeners",
    b"ref",
    b"release",
    b"removeAllListeners",
    b"removeListener",
    b"report",
    b"resourceUsage",
    b"reallyExit",
    b"setMaxListeners",
    b"setSourceMapsEnabled",
    b"send",
    b"sourceMapsEnabled",
    b"stderr",
    b"stdin",
    b"stdout",
    b"title",
    b"unref",
    b"uptime",
    b"version",
    b"versions",
];

const PROCESS_DEFAULT_KEYS: &[&[u8]] = &[
    b"_debugEnd",
    b"_debugProcess",
    b"_events",
    b"_eventsCount",
    b"_exiting",
    b"_fatalException",
    b"_getActiveHandles",
    b"_getActiveRequests",
    b"_kill",
    b"_linkedBinding",
    b"_maxListeners",
    b"_preload_modules",
    b"_rawDebug",
    b"_startProfilerIdleNotifier",
    b"_stopProfilerIdleNotifier",
    b"_tickCallback",
    b"abort",
    b"addListener",
    b"addUncaughtExceptionCaptureCallback",
    b"allowedNodeEnvironmentFlags",
    b"argv",
    b"argv0",
    b"arch",
    b"binding",
    b"channel",
    b"chdir",
    b"config",
    b"connected",
    b"cpuUsage",
    b"cwd",
    b"debugPort",
    b"disconnect",
    b"dlopen",
    b"domain",
    b"env",
    b"eventNames",
    b"execve",
    b"ref",
    b"unref",
    b"execArgv",
    b"execPath",
    b"features",
    b"finalization",
    b"getActiveResourcesInfo",
    b"getBuiltinModule",
    b"getMaxListeners",
    b"hrtime",
    b"kill",
    b"listenerCount",
    b"listeners",
    b"memoryUsage",
    b"moduleLoadList",
    b"nextTick",
    b"off",
    b"on",
    b"once",
    b"openStdin",
    b"pid",
    b"platform",
    b"ppid",
    b"prependListener",
    b"prependOnceListener",
    b"rawListeners",
    b"release",
    b"removeAllListeners",
    b"removeListener",
    b"report",
    b"resourceUsage",
    b"reallyExit",
    b"setMaxListeners",
    b"setSourceMapsEnabled",
    b"send",
    b"sourceMapsEnabled",
    b"stderr",
    b"stdin",
    b"stdout",
    b"title",
    b"uptime",
    b"version",
    b"versions",
];

const BUFFER_NAMESPACE_KEYS: &[&[u8]] = &[
    b"Buffer",
    b"transcode",
    b"isUtf8",
    b"isAscii",
    b"kMaxLength",
    b"kStringMaxLength",
    b"btoa",
    b"atob",
    b"constants",
    b"INSPECT_MAX_BYTES",
    b"Blob",
    b"resolveObjectURL",
    b"File",
];

const TIMERS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"setTimeout",
    b"clearTimeout",
    b"setImmediate",
    b"clearImmediate",
    b"setInterval",
    b"clearInterval",
    b"promises",
];

const OS_DEFAULT_KEYS: &[&[u8]] = &[
    b"arch",
    b"availableParallelism",
    b"cpus",
    b"endianness",
    b"freemem",
    b"getPriority",
    b"homedir",
    b"hostname",
    b"loadavg",
    b"networkInterfaces",
    b"platform",
    b"release",
    b"setPriority",
    b"tmpdir",
    b"totalmem",
    b"type",
    b"userInfo",
    b"uptime",
    b"version",
    b"machine",
    b"constants",
    b"EOL",
    b"devNull",
];

const OS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"EOL",
    b"arch",
    b"availableParallelism",
    b"constants",
    b"cpus",
    b"default",
    b"devNull",
    b"endianness",
    b"freemem",
    b"getPriority",
    b"homedir",
    b"hostname",
    b"loadavg",
    b"machine",
    b"networkInterfaces",
    b"platform",
    b"release",
    b"setPriority",
    b"tmpdir",
    b"totalmem",
    b"type",
    b"uptime",
    b"userInfo",
    b"version",
];

const PATH_DEFAULT_KEYS: &[&[u8]] = &[
    b"resolve",
    b"normalize",
    b"isAbsolute",
    b"join",
    b"relative",
    b"toNamespacedPath",
    b"dirname",
    b"basename",
    b"extname",
    b"format",
    b"parse",
    b"matchesGlob",
    b"sep",
    b"delimiter",
    b"win32",
    b"posix",
    b"_makeLong",
];

const PATH_NAMESPACE_KEYS: &[&[u8]] = &[
    b"_makeLong",
    b"basename",
    b"default",
    b"delimiter",
    b"dirname",
    b"extname",
    b"format",
    b"isAbsolute",
    b"join",
    b"matchesGlob",
    b"normalize",
    b"parse",
    b"posix",
    b"relative",
    b"resolve",
    b"sep",
    b"toNamespacedPath",
    b"win32",
];

const QUERYSTRING_DEFAULT_KEYS: &[&[u8]] = &[
    b"unescapeBuffer",
    b"unescape",
    b"escape",
    b"stringify",
    b"encode",
    b"parse",
    b"decode",
];

const QUERYSTRING_NAMESPACE_KEYS: &[&[u8]] = &[
    b"decode",
    b"default",
    b"encode",
    b"escape",
    b"parse",
    b"stringify",
    b"unescape",
    b"unescapeBuffer",
];

const PUNYCODE_DEFAULT_KEYS: &[&[u8]] = &[
    b"version",
    b"ucs2",
    b"decode",
    b"encode",
    b"toASCII",
    b"toUnicode",
];

const PUNYCODE_NAMESPACE_KEYS: &[&[u8]] = &[
    b"decode",
    b"default",
    b"encode",
    b"toASCII",
    b"toUnicode",
    b"ucs2",
    b"version",
];

const PUNYCODE_UCS2_KEYS: &[&[u8]] = &[b"decode", b"encode"];

const INSPECTOR_NAMESPACE_KEYS: &[&[u8]] = &[
    b"open",
    b"close",
    b"url",
    b"waitForDebugger",
    b"console",
    b"Session",
    b"Network",
];

const INSPECTOR_NETWORK_KEYS: &[&[u8]] = &[
    b"requestWillBeSent",
    b"responseReceived",
    b"loadingFinished",
    b"loadingFailed",
    b"dataSent",
    b"dataReceived",
    b"webSocketCreated",
    b"webSocketClosed",
    b"webSocketHandshakeResponseReceived",
];

const FS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"_toUnixTimestamp",
    b"access",
    b"accessSync",
    b"appendFile",
    b"appendFileSync",
    b"chmod",
    b"chmodSync",
    b"chown",
    b"chownSync",
    b"close",
    b"closeSync",
    b"constants",
    b"copyFile",
    b"copyFileSync",
    b"cp",
    b"cpSync",
    b"createReadStream",
    b"createWriteStream",
    b"exists",
    b"existsSync",
    b"fchmod",
    b"fchmodSync",
    b"fchown",
    b"fchownSync",
    b"fdatasync",
    b"fdatasyncSync",
    b"fstat",
    b"fstatSync",
    b"fsync",
    b"fsyncSync",
    b"ftruncate",
    b"ftruncateSync",
    b"futimes",
    b"futimesSync",
    b"glob",
    b"globSync",
    b"lchmod",
    b"lchmodSync",
    b"lchown",
    b"lchownSync",
    b"link",
    b"linkSync",
    b"lstat",
    b"lstatSync",
    b"lutimes",
    b"lutimesSync",
    b"mkdir",
    b"mkdirSync",
    b"mkdtemp",
    b"mkdtempSync",
    b"open",
    b"openSync",
    b"opendir",
    b"opendirSync",
    b"promises",
    b"read",
    b"readFile",
    b"readFileSync",
    b"readSync",
    b"readdir",
    b"readdirSync",
    b"readlink",
    b"readlinkSync",
    b"readv",
    b"readvSync",
    b"realpath",
    b"realpathSync",
    b"rename",
    b"renameSync",
    b"rm",
    b"rmSync",
    b"rmdir",
    b"rmdirSync",
    b"stat",
    b"statSync",
    b"statfs",
    b"statfsSync",
    b"symlink",
    b"symlinkSync",
    b"truncate",
    b"truncateSync",
    b"unlink",
    b"unlinkSync",
    b"unwatchFile",
    b"utimes",
    b"utimesSync",
    b"watch",
    b"watchFile",
    b"write",
    b"writeFile",
    b"writeFileSync",
    b"writeSync",
    b"writev",
    b"writevSync",
];

const URL_DEFAULT_KEYS: &[&[u8]] = &[
    b"Url",
    b"parse",
    b"resolve",
    b"resolveObject",
    b"format",
    b"URL",
    b"URLSearchParams",
    b"URLPattern",
    b"domainToASCII",
    b"domainToUnicode",
    b"pathToFileURL",
    b"fileURLToPath",
    b"fileURLToPathBuffer",
    b"urlToHttpOptions",
];

const URL_NAMESPACE_KEYS: &[&[u8]] = &[
    b"URL",
    b"URLSearchParams",
    b"URLPattern",
    b"Url",
    b"default",
    b"domainToASCII",
    b"domainToUnicode",
    b"fileURLToPath",
    b"fileURLToPathBuffer",
    b"format",
    b"parse",
    b"pathToFileURL",
    b"resolve",
    b"resolveObject",
    b"urlToHttpOptions",
];

const UTIL_DEFAULT_KEYS: &[&[u8]] = &[
    b"aborted",
    b"callbackify",
    b"convertProcessSignalToExitCode",
    b"debug",
    b"debuglog",
    b"deprecate",
    b"diff",
    b"format",
    b"formatWithOptions",
    b"getCallSites",
    b"getSystemErrorMap",
    b"getSystemErrorName",
    b"getSystemErrorMessage",
    b"inherits",
    b"inspect",
    b"isArray",
    b"isDeepStrictEqual",
    b"promisify",
    b"stripVTControlCharacters",
    b"styleText",
    b"toUSVString",
    b"setTraceSigInt",
    b"types",
    b"parseArgs",
    b"TextDecoder",
    b"TextEncoder",
    b"transferableAbortController",
    b"transferableAbortSignal",
];

const UTIL_NAMESPACE_KEYS: &[&[u8]] = &[
    b"_errnoException",
    b"_exceptionWithHostPort",
    b"_extend",
    b"aborted",
    b"callbackify",
    b"convertProcessSignalToExitCode",
    b"debug",
    b"debuglog",
    b"default",
    b"deprecate",
    b"diff",
    b"format",
    b"formatWithOptions",
    b"getCallSites",
    b"getSystemErrorMap",
    b"getSystemErrorName",
    b"getSystemErrorMessage",
    b"inherits",
    b"inspect",
    b"isArray",
    b"isDeepStrictEqual",
    b"promisify",
    b"stripVTControlCharacters",
    b"styleText",
    b"toUSVString",
    b"setTraceSigInt",
    b"types",
    b"parseArgs",
    b"MIMEParams",
    b"MIMEType",
    b"TextDecoder",
    b"TextEncoder",
    b"transferableAbortController",
    b"transferableAbortSignal",
];

const EVENTS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"EventEmitter",
    b"EventEmitterAsyncResource",
    b"default",
    b"defaultMaxListeners",
    b"usingDomains",
    b"captureRejections",
    b"captureRejectionSymbol",
    b"errorMonitor",
    b"init",
    b"listenerCount",
    b"on",
    b"once",
    b"addAbortListener",
    b"getEventListeners",
    b"getMaxListeners",
    b"setMaxListeners",
];

const REPL_NAMESPACE_KEYS: &[&[u8]] = &[
    b"REPLServer",
    b"REPL_MODE_SLOPPY",
    b"REPL_MODE_STRICT",
    b"Recoverable",
    b"builtinModules",
    b"start",
];

const WORKER_THREADS_NAMESPACE_KEYS: &[&[u8]] = &[
    b"BroadcastChannel",
    b"MessageChannel",
    b"MessagePort",
    b"SHARE_ENV",
    b"Worker",
    b"getEnvironmentData",
    b"isInternalThread",
    b"isMainThread",
    b"isMarkedAsUntransferable",
    b"locks",
    b"markAsUncloneable",
    b"markAsUntransferable",
    b"moveMessagePortToContext",
    b"parentPort",
    b"postMessageToThread",
    b"receiveMessageOnPort",
    b"resourceLimits",
    b"setEnvironmentData",
    b"threadId",
    b"threadName",
    b"workerData",
];

const VM_NAMESPACE_KEYS: &[&[u8]] = &[
    b"Script",
    b"createContext",
    b"createScript",
    b"runInContext",
    b"runInNewContext",
    b"runInThisContext",
    b"isContext",
    b"compileFunction",
    b"measureMemory",
    b"constants",
];

const VM_MODULE_NAMESPACE_KEYS: &[&[u8]] = &[
    b"Script",
    b"createContext",
    b"createScript",
    b"runInContext",
    b"runInNewContext",
    b"runInThisContext",
    b"isContext",
    b"compileFunction",
    b"measureMemory",
    b"constants",
    b"Module",
    b"SourceTextModule",
    b"SyntheticModule",
];

const VM_CONSTANTS_KEYS: &[&[u8]] = &[b"USE_MAIN_CONTEXT_DEFAULT_LOADER", b"DONT_CONTEXTIFY"];

// Linux-only open() flags: Node only enumerates these on platforms whose libc
// defines them (e.g. `O_DIRECT`/`O_NOATIME` are absent on macOS), so gate the
// enumerable-key tail by target so `Object.keys(constants)` matches Node here.
#[cfg(target_os = "linux")]
fn deprecated_constants_keys() -> &'static [&'static [u8]] {
    use std::sync::OnceLock;
    static MERGED: OnceLock<Vec<&'static [u8]>> = OnceLock::new();
    MERGED
        .get_or_init(|| {
            let mut v: Vec<&'static [u8]> = Vec::with_capacity(DEPRECATED_CONSTANTS_KEYS.len() + 6);
            for &k in DEPRECATED_CONSTANTS_KEYS {
                if k == b"SIGCHLD" {
                    v.push(k);
                    v.push(b"SIGSTKFLT");
                    continue;
                }
                if k == b"SIGIO" {
                    v.push(k);
                    v.push(b"SIGPOLL");
                    v.push(b"SIGPWR");
                    continue;
                }
                if k == b"RTLD_LOCAL" {
                    v.push(k);
                    #[cfg(target_env = "gnu")]
                    v.push(b"RTLD_DEEPBIND");
                    continue;
                }
                if k == b"defaultCoreCipherList" {
                    v.push(b"O_DIRECT");
                    v.push(b"O_NOATIME");
                }
                v.push(k);
            }
            v
        })
        .as_slice()
}

#[cfg(target_os = "macos")]
fn deprecated_constants_keys() -> &'static [&'static [u8]] {
    use std::sync::OnceLock;
    static MERGED: OnceLock<Vec<&'static [u8]>> = OnceLock::new();
    MERGED
        .get_or_init(|| {
            let mut v: Vec<&'static [u8]> = Vec::with_capacity(DEPRECATED_CONSTANTS_KEYS.len() + 2);
            for &k in DEPRECATED_CONSTANTS_KEYS {
                if k == b"SIGSYS" {
                    v.push(k);
                    v.push(b"SIGINFO");
                    continue;
                }
                if k == b"defaultCoreCipherList" {
                    v.push(b"O_SYMLINK");
                }
                v.push(k);
            }
            v
        })
        .as_slice()
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn deprecated_constants_keys() -> &'static [&'static [u8]] {
    DEPRECATED_CONSTANTS_KEYS
}

fn deprecated_constants_namespace_keys() -> &'static [&'static [u8]] {
    use std::sync::OnceLock;
    static MERGED: OnceLock<Vec<&'static [u8]>> = OnceLock::new();
    MERGED
        .get_or_init(|| {
            let keys = deprecated_constants_keys();
            let mut v: Vec<&'static [u8]> = Vec::with_capacity(keys.len() + 1);
            v.extend_from_slice(keys);
            v.push(b"default");
            v
        })
        .as_slice()
}

#[cfg(test)]
mod tests {
    use super::deprecated_constants_keys;

    #[test]
    fn rtld_deepbind_key_is_platform_gated() {
        let has_rtld_deepbind = deprecated_constants_keys()
            .iter()
            .any(|key| *key == b"RTLD_DEEPBIND");
        assert_eq!(
            has_rtld_deepbind,
            cfg!(all(target_os = "linux", target_env = "gnu"))
        );
    }
}

const FS_NAMESPACE_EXPORT_KEYS: &[&[u8]] = &[
    b"appendFile",
    b"appendFileSync",
    b"access",
    b"accessSync",
    b"chown",
    b"chownSync",
    b"chmod",
    b"chmodSync",
    b"close",
    b"closeSync",
    b"copyFile",
    b"copyFileSync",
    b"cp",
    b"cpSync",
    b"createReadStream",
    b"createWriteStream",
    b"exists",
    b"existsSync",
    b"fchown",
    b"fchownSync",
    b"fchmod",
    b"fchmodSync",
    b"fdatasync",
    b"fdatasyncSync",
    b"fstat",
    b"fstatSync",
    b"fsync",
    b"fsyncSync",
    b"ftruncate",
    b"ftruncateSync",
    b"futimes",
    b"futimesSync",
    b"glob",
    b"globSync",
    b"lchown",
    b"lchownSync",
    b"lchmod",
    b"lchmodSync",
    b"link",
    b"linkSync",
    b"lstat",
    b"lstatSync",
    b"lutimes",
    b"lutimesSync",
    b"mkdir",
    b"mkdirSync",
    b"mkdtemp",
    b"mkdtempDisposableSync",
    b"mkdtempSync",
    b"open",
    b"openAsBlob",
    b"openSync",
    b"readdir",
    b"readdirSync",
    b"read",
    b"readSync",
    b"readv",
    b"readvSync",
    b"readFile",
    b"readFileSync",
    b"readlink",
    b"readlinkSync",
    b"realpath",
    b"realpathSync",
    b"rename",
    b"renameSync",
    b"rm",
    b"rmSync",
    b"rmdir",
    b"rmdirSync",
    b"stat",
    b"statfs",
    b"statSync",
    b"statfsSync",
    b"symlink",
    b"symlinkSync",
    b"truncate",
    b"truncateSync",
    b"unwatchFile",
    b"unlink",
    b"unlinkSync",
    b"utimes",
    b"utimesSync",
    b"watch",
    b"watchFile",
    b"writeFile",
    b"writeFileSync",
    b"write",
    b"writeSync",
    b"writev",
    b"writevSync",
    b"Dirent",
    b"Stats",
    b"ReadStream",
    b"WriteStream",
    b"FileReadStream",
    b"FileWriteStream",
    b"Utf8Stream",
    b"_toUnixTimestamp",
    b"Dir",
    b"opendir",
    b"opendirSync",
    b"constants",
    b"promises",
];

const SQLITE_CONSTANTS_KEYS: &[&[u8]] = &[
    b"SQLITE_CHANGESET_DATA",
    b"SQLITE_CHANGESET_NOTFOUND",
    b"SQLITE_CHANGESET_CONFLICT",
    b"SQLITE_CHANGESET_CONSTRAINT",
    b"SQLITE_CHANGESET_FOREIGN_KEY",
    b"SQLITE_CHANGESET_OMIT",
    b"SQLITE_CHANGESET_REPLACE",
    b"SQLITE_CHANGESET_ABORT",
    b"SQLITE_OK",
    b"SQLITE_DENY",
    b"SQLITE_IGNORE",
    b"SQLITE_CREATE_INDEX",
    b"SQLITE_CREATE_TABLE",
    b"SQLITE_CREATE_TEMP_INDEX",
    b"SQLITE_CREATE_TEMP_TABLE",
    b"SQLITE_CREATE_TEMP_TRIGGER",
    b"SQLITE_CREATE_TEMP_VIEW",
    b"SQLITE_CREATE_TRIGGER",
    b"SQLITE_CREATE_VIEW",
    b"SQLITE_DELETE",
    b"SQLITE_DROP_INDEX",
    b"SQLITE_DROP_TABLE",
    b"SQLITE_DROP_TEMP_INDEX",
    b"SQLITE_DROP_TEMP_TABLE",
    b"SQLITE_DROP_TEMP_TRIGGER",
    b"SQLITE_DROP_TEMP_VIEW",
    b"SQLITE_DROP_TRIGGER",
    b"SQLITE_DROP_VIEW",
    b"SQLITE_INSERT",
    b"SQLITE_PRAGMA",
    b"SQLITE_READ",
    b"SQLITE_SELECT",
    b"SQLITE_TRANSACTION",
    b"SQLITE_UPDATE",
    b"SQLITE_ATTACH",
    b"SQLITE_DETACH",
    b"SQLITE_ALTER_TABLE",
    b"SQLITE_REINDEX",
    b"SQLITE_ANALYZE",
    b"SQLITE_CREATE_VTABLE",
    b"SQLITE_DROP_VTABLE",
    b"SQLITE_FUNCTION",
    b"SQLITE_SAVEPOINT",
    b"SQLITE_COPY",
    b"SQLITE_RECURSIVE",
];

const SEA_NAMESPACE_KEYS: &[&[u8]] = &[
    b"default",
    b"getAsset",
    b"getAssetAsBlob",
    b"getAssetKeys",
    b"getRawAsset",
    b"isSea",
];

const SEA_DEFAULT_KEYS: &[&[u8]] = &[
    b"isSea",
    b"getAsset",
    b"getRawAsset",
    b"getAssetAsBlob",
    b"getAssetKeys",
];

pub(crate) fn native_module_enumerable_keys(module_name: &str) -> Option<&'static [&'static [u8]]> {
    let module_name = normalize_native_module_alias(module_name);
    match module_name {
        "fs" => Some(FS_NAMESPACE_EXPORT_KEYS),
        "async_hooks" => Some(ASYNC_HOOKS_NAMESPACE_KEYS),
        "async_hooks.default" => Some(ASYNC_HOOKS_DEFAULT_KEYS),
        "assert/strict" => Some(&[
            b"Assert",
            b"AssertionError",
            b"ok",
            b"fail",
            b"equal",
            b"notEqual",
            b"deepEqual",
            b"notDeepEqual",
            b"deepStrictEqual",
            b"notDeepStrictEqual",
            b"strictEqual",
            b"notStrictEqual",
            b"partialDeepStrictEqual",
            b"match",
            b"doesNotMatch",
            b"throws",
            b"rejects",
            b"doesNotThrow",
            b"doesNotReject",
            b"ifError",
            b"strict",
        ]),
        "buffer.constants" => Some(&[b"MAX_LENGTH", b"MAX_STRING_LENGTH"]),
        "sqlite" => Some(&[
            b"DatabaseSync",
            b"Session",
            b"StatementSync",
            b"backup",
            b"constants",
            b"default",
        ]),
        "sqlite.constants" => Some(SQLITE_CONSTANTS_KEYS),
        "sea" => Some(SEA_NAMESPACE_KEYS),
        "sea.default" => Some(SEA_DEFAULT_KEYS),
        "domain" => Some(&[b"_stack", b"Domain", b"createDomain", b"create", b"active"]),
        // #3677: zlib.constants enumerates the full Z_*/BROTLI_*/ZSTD_* table.
        "zlib.constants" => Some(ZLIB_CONSTANTS_KEYS),
        // Deprecated path alias enumerable on the top-level and style
        // sub-namespaces, matching Node's `Object.keys(...).includes`.
        "path" => Some(PATH_NAMESPACE_KEYS),
        "path.default" | "path.posix.default" | "path.win32.default" => Some(PATH_DEFAULT_KEYS),
        "path.posix" | "path.win32" => Some(PATH_NAMESPACE_KEYS),
        "fs" => Some(FS_NAMESPACE_KEYS),
        "constants" => Some(deprecated_constants_namespace_keys()),
        "constants.default" => Some(deprecated_constants_keys()),
        "dns" => Some(DNS_NAMESPACE_KEYS),
        "dns.default" => Some(DNS_DEFAULT_KEYS),
        "dns/promises" => Some(DNS_PROMISES_NAMESPACE_KEYS),
        "dns/promises.default" => Some(DNS_PROMISES_DEFAULT_KEYS),
        "child_process" => Some(CHILD_PROCESS_NAMESPACE_KEYS),
        "child_process.default" => Some(CHILD_PROCESS_DEFAULT_KEYS),
        "node-pty" => Some(NODE_PTY_NAMESPACE_KEYS),
        "node-pty.default" => Some(NODE_PTY_DEFAULT_KEYS),
        "cluster" => Some(CLUSTER_NAMESPACE_KEYS),
        "cluster.default" => Some(CLUSTER_DEFAULT_KEYS),
        "stream" => Some(STREAM_NAMESPACE_KEYS),
        "process" => Some(PROCESS_DEFAULT_KEYS),
        "process.namespace" => Some(PROCESS_NAMESPACE_KEYS),
        "process.default" => Some(PROCESS_DEFAULT_KEYS),
        "buffer" => Some(BUFFER_NAMESPACE_KEYS),
        "querystring" => Some(QUERYSTRING_NAMESPACE_KEYS),
        "querystring.default" => Some(QUERYSTRING_DEFAULT_KEYS),
        "console" | "console.default" => Some(&[
            b"log",
            b"info",
            b"debug",
            b"warn",
            b"error",
            b"dir",
            b"time",
            b"timeEnd",
            b"timeLog",
            b"trace",
            b"assert",
            b"clear",
            b"count",
            b"countReset",
            b"group",
            b"groupEnd",
            b"table",
            b"dirxml",
            b"groupCollapsed",
            b"Console",
            b"profile",
            b"profileEnd",
            b"timeStamp",
            b"context",
            b"createTask",
        ]),
        "punycode" => Some(PUNYCODE_NAMESPACE_KEYS),
        "punycode.default" => Some(PUNYCODE_DEFAULT_KEYS),
        "punycode.ucs2" => Some(PUNYCODE_UCS2_KEYS),
        "inspector" | "inspector.default" => Some(INSPECTOR_NAMESPACE_KEYS),
        "inspector.Network" => Some(INSPECTOR_NETWORK_KEYS),
        "timers" => Some(TIMERS_NAMESPACE_KEYS),
        "os" => Some(OS_NAMESPACE_KEYS),
        "os.default" => Some(OS_DEFAULT_KEYS),
        "url" => Some(URL_NAMESPACE_KEYS),
        "url.default" => Some(URL_DEFAULT_KEYS),
        "util" => Some(UTIL_NAMESPACE_KEYS),
        "util.default" => Some(UTIL_DEFAULT_KEYS),
        "net" => Some(&[
            b"BlockList",
            b"_createServerHandle",
            b"_normalizeArgs",
            b"connect",
            b"createConnection",
            b"createServer",
            b"isIP",
            b"isIPv4",
            b"isIPv6",
            b"Server",
            b"Socket",
            b"SocketAddress",
            b"Stream",
            b"getDefaultAutoSelectFamily",
            b"setDefaultAutoSelectFamily",
            b"getDefaultAutoSelectFamilyAttemptTimeout",
            b"setDefaultAutoSelectFamilyAttemptTimeout",
        ]),
        "http" | "http.default" => Some(&[
            b"METHODS",
            b"STATUS_CODES",
            b"createServer",
            b"Server",
            b"IncomingMessage",
            b"OutgoingMessage",
            b"ServerResponse",
            b"ClientRequest",
            b"Agent",
            b"WebSocket",
            b"_connectionListener",
            b"get",
            b"request",
            b"maxHeaderSize",
            b"globalAgent",
            b"validateHeaderName",
            b"validateHeaderValue",
            b"setMaxIdleHTTPParsers",
            b"setGlobalProxyFromEnv",
        ]),
        "https" => Some(&[
            b"Agent",
            b"Server",
            b"createServer",
            b"get",
            b"request",
            b"globalAgent",
        ]),
        "http2" => Some(crate::node_http2_constants::HTTP2_NAMESPACE_KEYS),
        "http2.constants" => Some(crate::node_http2_constants::HTTP2_CONSTANTS_KEYS),
        // #3906: native-module default/namespace objects previously enumerated
        // only the internal `__module__` sentinel. List each module's supported
        // export surface (the same set the api-manifest / docs / DTS expose and
        // that `hasOwnProperty` / named imports agree on) so `Object.keys(mod)`
        // matches Node. tty / perf_hooks / util.types are byte-identical to
        // Node; v8 lists the exports Perry implements. Key order follows Node's.
        "tty" => Some(&[b"isatty", b"ReadStream", b"WriteStream"]),
        "v8" => Some(&[
            b"cachedDataVersionTag",
            b"getHeapSnapshot",
            b"getHeapStatistics",
            b"getHeapSpaceStatistics",
            b"getHeapCodeStatistics",
            b"setFlagsFromString",
            b"Serializer",
            b"Deserializer",
            b"DefaultSerializer",
            b"DefaultDeserializer",
            b"deserialize",
            b"takeCoverage",
            b"stopCoverage",
            b"serialize",
            b"writeHeapSnapshot",
            b"promiseHooks",
            b"startupSnapshot",
            b"setHeapSnapshotNearHeapLimit",
            b"GCProfiler",
        ]),
        "perf_hooks" => Some(&[
            b"Performance",
            b"PerformanceEntry",
            b"PerformanceMark",
            b"PerformanceMeasure",
            b"PerformanceObserver",
            b"PerformanceObserverEntryList",
            b"PerformanceResourceTiming",
            b"monitorEventLoopDelay",
            b"eventLoopUtilization",
            b"timerify",
            b"createHistogram",
            b"performance",
            b"constants",
        ]),
        // The util/types namespace object is tagged `util.types` internally
        // (see the `callable_module_name` remap below); accept both spellings.
        "util/types" | "util.types" => Some(&[
            b"isArgumentsObject",
            b"isArrayBuffer",
            b"isAsyncFunction",
            b"isBigIntObject",
            b"isBooleanObject",
            b"isDate",
            b"isExternal",
            b"isGeneratorFunction",
            b"isGeneratorObject",
            b"isMap",
            b"isMapIterator",
            b"isModuleNamespaceObject",
            b"isNativeError",
            b"isNumberObject",
            b"isPromise",
            b"isProxy",
            b"isRegExp",
            b"isSet",
            b"isSetIterator",
            b"isSharedArrayBuffer",
            b"isStringObject",
            b"isSymbolObject",
            b"isWeakMap",
            b"isWeakSet",
            b"isAnyArrayBuffer",
            b"isBoxedPrimitive",
            b"isArrayBufferView",
            b"isDataView",
            b"isTypedArray",
            b"isUint8Array",
            b"isUint8ClampedArray",
            b"isUint16Array",
            b"isUint32Array",
            b"isInt8Array",
            b"isInt16Array",
            b"isInt32Array",
            b"isFloat16Array",
            b"isFloat32Array",
            b"isFloat64Array",
            b"isBigInt64Array",
            b"isBigUint64Array",
            b"isKeyObject",
            b"isCryptoKey",
        ]),
        "events" => Some(EVENTS_NAMESPACE_KEYS),
        "repl" | "repl.default" => Some(REPL_NAMESPACE_KEYS),
        "worker_threads" => Some(WORKER_THREADS_NAMESPACE_KEYS),
        "vm" => Some(if crate::node_vm::vm_modules_enabled() {
            VM_MODULE_NAMESPACE_KEYS
        } else {
            VM_NAMESPACE_KEYS
        }),
        "vm.constants" => Some(VM_CONSTANTS_KEYS),
        // Plain `timers` was missing — `require('node:timers').setImmediate`
        // read undefined (Next.js's fast-set-immediate extension reads and
        // patches it at module init).
        "timers" => Some(&[
            b"setTimeout",
            b"clearTimeout",
            b"setInterval",
            b"clearInterval",
            b"setImmediate",
            b"clearImmediate",
            b"promises",
        ]),
        "timers/promises" => Some(&[b"setTimeout", b"setImmediate", b"setInterval", b"scheduler"]),
        "readline/promises" => Some(&[b"Interface", b"Readline", b"createInterface"]),
        "zlib" => Some(&[b"codes"]),
        "tls" => Some(&[
            b"checkServerIdentity",
            b"connect",
            b"createServer",
            b"createSecureContext",
            b"getCACertificates",
            b"getCiphers",
            b"setDefaultCACertificates",
            b"Server",
            b"SecureContext",
            b"TLSSocket",
            b"DEFAULT_ECDH_CURVE",
            b"DEFAULT_MAX_VERSION",
            b"DEFAULT_MIN_VERSION",
            b"DEFAULT_CIPHERS",
            b"rootCertificates",
            b"CLIENT_RENEG_LIMIT",
            b"CLIENT_RENEG_WINDOW",
        ]),
        _ => None,
    }
}

pub(crate) fn native_module_has_enumerable_key(module_name: &str, key: &str) -> bool {
    if matches!(
        module_name,
        "process" | "process.namespace" | "process.default"
    ) && key == "permission"
    {
        return crate::process::process_permission_enabled();
    }
    native_module_enumerable_keys(module_name).is_some_and(|keys| keys.contains(&key.as_bytes()))
}
