//! `API_MANIFEST` entries, part 3. Split out of entries.rs to satisfy the
//! 2000-line file-size gate; concatenated at compile time by the parent.
//!
//! `use super::*` pulls in the parent's type imports and the const-fn entry
//! builders (`method`/`property`/`class`/…) — children can name an ancestor's
//! private items, so the builders need no visibility change.

use super::*;

pub(crate) const API_MANIFEST_PART_3: &[ApiEntry] = &[
    property("constants", "O_SYMLINK"),
    property("constants", "O_CREAT"),
    property("constants", "O_TRUNC"),
    property("constants", "O_APPEND"),
    property("constants", "O_EXCL"),
    property("constants", "UV_FS_O_FILEMAP"),
    property("constants", "UV_FS_SYMLINK_DIR"),
    property("constants", "UV_FS_SYMLINK_JUNCTION"),
    property("constants", "UV_FS_COPYFILE_EXCL"),
    property("constants", "UV_FS_COPYFILE_FICLONE"),
    property("constants", "UV_FS_COPYFILE_FICLONE_FORCE"),
    property("constants", "UV_DIRENT_UNKNOWN"),
    property("constants", "UV_DIRENT_FILE"),
    property("constants", "UV_DIRENT_DIR"),
    property("constants", "UV_DIRENT_LINK"),
    property("constants", "UV_DIRENT_FIFO"),
    property("constants", "UV_DIRENT_SOCKET"),
    property("constants", "UV_DIRENT_CHAR"),
    property("constants", "UV_DIRENT_BLOCK"),
    property("constants", "COPYFILE_EXCL"),
    property("constants", "COPYFILE_FICLONE"),
    property("constants", "COPYFILE_FICLONE_FORCE"),
    property("constants", "S_IFMT"),
    property("constants", "S_IFREG"),
    property("constants", "S_IFDIR"),
    property("constants", "S_IFCHR"),
    property("constants", "S_IFBLK"),
    property("constants", "S_IFIFO"),
    property("constants", "S_IFLNK"),
    property("constants", "S_IFSOCK"),
    property("constants", "S_IRWXU"),
    property("constants", "S_IRUSR"),
    property("constants", "S_IWUSR"),
    property("constants", "S_IXUSR"),
    property("constants", "S_IRWXG"),
    property("constants", "S_IRGRP"),
    property("constants", "S_IWGRP"),
    property("constants", "S_IXGRP"),
    property("constants", "S_IRWXO"),
    property("constants", "S_IROTH"),
    property("constants", "S_IWOTH"),
    property("constants", "S_IXOTH"),
    property("constants", "SIGHUP"),
    property("constants", "SIGINT"),
    property("constants", "SIGQUIT"),
    property("constants", "SIGILL"),
    property("constants", "SIGTRAP"),
    property("constants", "SIGABRT"),
    property("constants", "SIGIOT"),
    property("constants", "SIGBUS"),
    property("constants", "SIGFPE"),
    property("constants", "SIGKILL"),
    property("constants", "SIGUSR1"),
    property("constants", "SIGSEGV"),
    property("constants", "SIGUSR2"),
    property("constants", "SIGPIPE"),
    property("constants", "SIGALRM"),
    property("constants", "SIGTERM"),
    property("constants", "SIGCHLD"),
    property("constants", "SIGSTKFLT"),
    property("constants", "SIGCONT"),
    property("constants", "SIGSTOP"),
    property("constants", "SIGTSTP"),
    property("constants", "SIGTTIN"),
    property("constants", "SIGTTOU"),
    property("constants", "SIGURG"),
    property("constants", "SIGXCPU"),
    property("constants", "SIGXFSZ"),
    property("constants", "SIGVTALRM"),
    property("constants", "SIGPROF"),
    property("constants", "SIGWINCH"),
    property("constants", "SIGIO"),
    property("constants", "SIGPOLL"),
    property("constants", "SIGPWR"),
    property("constants", "SIGSYS"),
    property("constants", "SIGINFO"),
    property("constants", "E2BIG"),
    property("constants", "EACCES"),
    property("constants", "EADDRINUSE"),
    property("constants", "EADDRNOTAVAIL"),
    property("constants", "EAFNOSUPPORT"),
    property("constants", "EAGAIN"),
    property("constants", "EALREADY"),
    property("constants", "EBADF"),
    property("constants", "EBADMSG"),
    property("constants", "EBUSY"),
    property("constants", "ECANCELED"),
    property("constants", "ECHILD"),
    property("constants", "ECONNABORTED"),
    property("constants", "ECONNREFUSED"),
    property("constants", "ECONNRESET"),
    property("constants", "EDEADLK"),
    property("constants", "EDESTADDRREQ"),
    property("constants", "EDOM"),
    property("constants", "EDQUOT"),
    property("constants", "EEXIST"),
    property("constants", "EFAULT"),
    property("constants", "EFBIG"),
    property("constants", "EHOSTUNREACH"),
    property("constants", "EIDRM"),
    property("constants", "EILSEQ"),
    property("constants", "EINPROGRESS"),
    property("constants", "EINTR"),
    property("constants", "EINVAL"),
    property("constants", "EIO"),
    property("constants", "EISCONN"),
    property("constants", "EISDIR"),
    property("constants", "ELOOP"),
    property("constants", "EMFILE"),
    property("constants", "EMLINK"),
    property("constants", "EMSGSIZE"),
    property("constants", "EMULTIHOP"),
    property("constants", "ENAMETOOLONG"),
    property("constants", "ENETDOWN"),
    property("constants", "ENETRESET"),
    property("constants", "ENETUNREACH"),
    property("constants", "ENFILE"),
    property("constants", "ENOBUFS"),
    property("constants", "ENODATA"),
    property("constants", "ENODEV"),
    property("constants", "ENOENT"),
    property("constants", "ENOEXEC"),
    property("constants", "ENOLCK"),
    property("constants", "ENOLINK"),
    property("constants", "ENOMEM"),
    property("constants", "ENOMSG"),
    property("constants", "ENOPROTOOPT"),
    property("constants", "ENOSPC"),
    property("constants", "ENOSR"),
    property("constants", "ENOSTR"),
    property("constants", "ENOSYS"),
    property("constants", "ENOTCONN"),
    property("constants", "ENOTDIR"),
    property("constants", "ENOTEMPTY"),
    property("constants", "ENOTSOCK"),
    property("constants", "ENOTSUP"),
    property("constants", "ENOTTY"),
    property("constants", "ENXIO"),
    property("constants", "EOPNOTSUPP"),
    property("constants", "EOVERFLOW"),
    property("constants", "EPERM"),
    property("constants", "EPIPE"),
    property("constants", "EPROTO"),
    property("constants", "EPROTONOSUPPORT"),
    property("constants", "EPROTOTYPE"),
    property("constants", "ERANGE"),
    property("constants", "EROFS"),
    property("constants", "ESPIPE"),
    property("constants", "ESRCH"),
    property("constants", "ESTALE"),
    property("constants", "ETIME"),
    property("constants", "ETIMEDOUT"),
    property("constants", "ETXTBSY"),
    property("constants", "EWOULDBLOCK"),
    property("constants", "EXDEV"),
    property("constants", "PRIORITY_LOW"),
    property("constants", "PRIORITY_BELOW_NORMAL"),
    property("constants", "PRIORITY_NORMAL"),
    property("constants", "PRIORITY_ABOVE_NORMAL"),
    property("constants", "PRIORITY_HIGH"),
    property("constants", "PRIORITY_HIGHEST"),
    property("constants", "RTLD_LAZY"),
    property("constants", "RTLD_NOW"),
    property("constants", "RTLD_GLOBAL"),
    property("constants", "RTLD_LOCAL"),
    property("constants", "RTLD_DEEPBIND"),
    property("constants", "OPENSSL_VERSION_NUMBER"),
    property("constants", "SSL_OP_ALL"),
    property("constants", "SSL_OP_ALLOW_NO_DHE_KEX"),
    property("constants", "SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION"),
    property("constants", "SSL_OP_CIPHER_SERVER_PREFERENCE"),
    property("constants", "SSL_OP_CISCO_ANYCONNECT"),
    property("constants", "SSL_OP_COOKIE_EXCHANGE"),
    property("constants", "SSL_OP_CRYPTOPRO_TLSEXT_BUG"),
    property("constants", "SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS"),
    property("constants", "SSL_OP_LEGACY_SERVER_CONNECT"),
    property("constants", "SSL_OP_NO_COMPRESSION"),
    property("constants", "SSL_OP_NO_ENCRYPT_THEN_MAC"),
    property("constants", "SSL_OP_NO_QUERY_MTU"),
    property("constants", "SSL_OP_NO_RENEGOTIATION"),
    property("constants", "SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION"),
    property("constants", "SSL_OP_NO_SSLv2"),
    property("constants", "SSL_OP_NO_SSLv3"),
    property("constants", "SSL_OP_NO_TICKET"),
    property("constants", "RSA_PKCS1_PADDING"),
    property("constants", "SSL_OP_NO_TLSv1"),
    property("constants", "SSL_OP_NO_TLSv1_1"),
    property("constants", "SSL_OP_NO_TLSv1_2"),
    property("constants", "SSL_OP_NO_TLSv1_3"),
    property("constants", "SSL_OP_PRIORITIZE_CHACHA"),
    property("constants", "SSL_OP_TLS_ROLLBACK_BUG"),
    property("constants", "ENGINE_METHOD_RSA"),
    property("constants", "ENGINE_METHOD_DSA"),
    property("constants", "ENGINE_METHOD_DH"),
    property("constants", "ENGINE_METHOD_RAND"),
    property("constants", "ENGINE_METHOD_EC"),
    property("constants", "ENGINE_METHOD_CIPHERS"),
    property("constants", "ENGINE_METHOD_DIGESTS"),
    property("constants", "ENGINE_METHOD_PKEY_METHS"),
    property("constants", "ENGINE_METHOD_PKEY_ASN1_METHS"),
    property("constants", "ENGINE_METHOD_ALL"),
    property("constants", "ENGINE_METHOD_NONE"),
    property("constants", "DH_CHECK_P_NOT_SAFE_PRIME"),
    property("constants", "DH_CHECK_P_NOT_PRIME"),
    property("constants", "DH_UNABLE_TO_CHECK_GENERATOR"),
    property("constants", "DH_NOT_SUITABLE_GENERATOR"),
    property("constants", "RSA_NO_PADDING"),
    property("constants", "RSA_PKCS1_OAEP_PADDING"),
    property("constants", "RSA_X931_PADDING"),
    property("constants", "RSA_PKCS1_PSS_PADDING"),
    property("constants", "RSA_PSS_SALTLEN_DIGEST"),
    property("constants", "RSA_PSS_SALTLEN_MAX_SIGN"),
    property("constants", "RSA_PSS_SALTLEN_AUTO"),
    property("constants", "TLS1_VERSION"),
    property("constants", "TLS1_1_VERSION"),
    property("constants", "TLS1_2_VERSION"),
    property("constants", "TLS1_3_VERSION"),
    property("constants", "defaultCoreCipherList"),
    property("constants", "POINT_CONVERSION_COMPRESSED"),
    property("constants", "POINT_CONVERSION_UNCOMPRESSED"),
    property("constants", "POINT_CONVERSION_HYBRID"),
    // path — methods mapped to Expr::Path* in expr_call.rs.
    property("path", "default"),
    method("path", "join", false, None),
    method("path", "dirname", false, None),
    method("path", "basename", false, None),
    method("path", "extname", false, None),
    method("path", "resolve", false, None),
    method("path", "isAbsolute", false, None),
    method("path", "relative", false, None),
    method("path", "normalize", false, None),
    method("path", "parse", false, None),
    method("path", "format", false, None),
    method("path", "toNamespacedPath", false, None),
    method("path", "_makeLong", false, None),
    method("path", "matchesGlob", false, None),
    property("path", "sep"),
    property("path", "delimiter"),
    property("path", "posix"),
    property("path", "win32"),
    // Direct Node path submodules. Runtime aliases `path/posix` and
    // `path/win32` to the existing `path.posix` / `path.win32`
    // native-module namespaces.
    property("path/posix", "default"),
    method("path/posix", "join", false, None),
    method("path/posix", "dirname", false, None),
    method("path/posix", "basename", false, None),
    method("path/posix", "extname", false, None),
    method("path/posix", "resolve", false, None),
    method("path/posix", "isAbsolute", false, None),
    method("path/posix", "relative", false, None),
    method("path/posix", "normalize", false, None),
    method("path/posix", "parse", false, None),
    method("path/posix", "format", false, None),
    method("path/posix", "toNamespacedPath", false, None),
    method("path/posix", "_makeLong", false, None),
    method("path/posix", "matchesGlob", false, None),
    property("path/posix", "sep"),
    property("path/posix", "delimiter"),
    property("path/posix", "posix"),
    property("path/posix", "win32"),
    property("path/win32", "default"),
    method("path/win32", "join", false, None),
    method("path/win32", "dirname", false, None),
    method("path/win32", "basename", false, None),
    method("path/win32", "extname", false, None),
    method("path/win32", "resolve", false, None),
    method("path/win32", "isAbsolute", false, None),
    method("path/win32", "relative", false, None),
    method("path/win32", "normalize", false, None),
    method("path/win32", "parse", false, None),
    method("path/win32", "format", false, None),
    method("path/win32", "toNamespacedPath", false, None),
    method("path/win32", "_makeLong", false, None),
    method("path/win32", "matchesGlob", false, None),
    property("path/win32", "sep"),
    property("path/win32", "delimiter"),
    property("path/win32", "posix"),
    property("path/win32", "win32"),
    // node:module - shape stubs plus runtime-backed builtin detection.
    property("module", "Module"),
    property("module", "builtinModules"),
    property("module", "constants"),
    property("module", "default"),
    property("module", "globalPaths"),
    property("module", "_cache"),
    property("module", "_extensions"),
    property("module", "_pathCache"),
    property("module", "wrap"),
    property("module", "wrapper"),
    method("module", "_findPath", false, None),
    method("module", "_initPaths", false, None),
    method("module", "_load", false, None),
    method("module", "_nodeModulePaths", false, None),
    method("module", "_preloadModules", false, None),
    method("module", "_resolveFilename", false, None),
    method("module", "_resolveLookupPaths", false, None),
    class("module", "Module"),
    method("module", "Module", false, None),
    method("module", "createRequire", false, None),
    method("module", "findPackageJSON", false, None),
    method("module", "findSourceMap", false, None),
    method("module", "flushCompileCache", false, None),
    method("module", "getCompileCacheDir", false, None),
    method("module", "getSourceMapsSupport", false, None),
    method("module", "register", false, None),
    method("module", "registerHooks", false, None),
    method("module", "runMain", false, None),
    method("module", "setSourceMapsSupport", false, None),
    method("module", "stripTypeScriptTypes", false, None),
    method("module", "syncBuiltinESMExports", false, None),
    method("module", "enableCompileCache", false, None),
    method("module", "isBuiltin", false, None),
    class("module", "SourceMap"),
    method("module", "SourceMap", false, None),
    // node:test — deterministic runner, mock tracker, timer, reporter, and
    // snapshot helpers used by the curated node-suite parity coverage.
    method("test", "default", false, None),
    method("test", "test", false, None),
    method("test", "skip", false, None),
    method("test", "todo", false, None),
    method("test", "only", false, None),
    method("test", "suite", false, None),
    method("test", "describe", false, None),
    method("test", "it", false, None),
    method("test", "before", false, None),
    method("test", "after", false, None),
    method("test", "beforeEach", false, None),
    method("test", "afterEach", false, None),
    method("test", "run", false, None),
    // #3719: Node's current `node:test` named exports — `expectFailure`
    // (function) and `assert` (assertion namespace object with `register`).
    method("test", "expectFailure", false, None),
    property("test", "assert"),
    property("test", "mock"),
    method("test", "fn", false, Some("mock")),
    method("test", "method", false, Some("mock")),
    method("test", "getter", false, Some("mock")),
    method("test", "setter", false, Some("mock")),
    method("test", "property", false, Some("mock")),
    method("test", "reset", false, Some("mock")),
    method("test", "restoreAll", false, Some("mock")),
    method("test", "enable", false, Some("timers")),
    method("test", "tick", false, Some("timers")),
    method("test", "runAll", false, Some("timers")),
    method("test", "setTime", false, Some("timers")),
    property("test", "snapshot"),
    method(
        "test",
        "setDefaultSnapshotSerializers",
        false,
        Some("snapshot"),
    ),
    method("test", "setResolveSnapshotPath", false, Some("snapshot")),
    // node:test/reporters — reporter constructors exposed by the runtime
    // submodule. Formatting behavior remains covered by the node:test suite.
    property("test/reporters", "default"),
    method("test/reporters", "spec", false, None),
    method("test/reporters", "tap", false, None),
    method("test/reporters", "dot", false, None),
    method("test/reporters", "junit", false, None),
    method("test/reporters", "lcov", false, None),
    // process — properties mapped to Expr::Process* / Expr::Os* in expr_member.rs.
    method("process", "abort", false, None),
    method("process", "cwd", false, None),
    method("process", "uptime", false, None),
    method("process", "memoryUsage", false, None),
    // #3108 (shipped in #3684): manifest rows for the source-map toggle
    // implemented in the native dispatch table. Without these the
    // manifest-consistency drift check fails.
    method("process", "sourceMapsEnabled", false, None),
    method("process", "setSourceMapsEnabled", false, None),
    method("process", "nextTick", false, None),
    method("process", "chdir", false, None),
    method("process", "kill", false, None),
    method("process", "getBuiltinModule", false, None),
    method("process", "execve", false, None),
    method("process", "ref", false, None),
    method("process", "unref", false, None),
    method("process", "binding", false, None),
    method("process", "_linkedBinding", false, None),
    method("process", "dlopen", false, None),
    method("process", "_rawDebug", false, None),
    method("process", "_debugProcess", false, None),
    method("process", "_debugEnd", false, None),
    method("process", "_startProfilerIdleNotifier", false, None),
    method("process", "_stopProfilerIdleNotifier", false, None),
    method("process", "reallyExit", false, None),
    method("process", "_fatalException", false, None),
    method("process", "_tickCallback", false, None),
    method("process", "_getActiveHandles", false, None),
    method("process", "_getActiveRequests", false, None),
    method("process", "openStdin", false, None),
    method("process", "_kill", false, None),
    property("process", "_eval"),
    property("process", "_events"),
    property("process", "_eventsCount"),
    property("process", "_exiting"),
    property("process", "_maxListeners"),
    property("process", "_preload_modules"),
    property("process", "domain"),
    method_sig(
        "process",
        "loadEnvFile",
        false,
        None,
        &[ParamSpec::Named {
            name: "path",
            ty: TypeSpec::Any,
            optional: true,
        }],
        TypeSpec::Void,
    ),
    method_sig(
        "process",
        "sourceMapsEnabled",
        false,
        None,
        &[],
        TypeSpec::Bool,
    ),
    method_sig(
        "process",
        "setSourceMapsEnabled",
        false,
        None,
        &[ParamSpec::Named {
            name: "enabled",
            ty: TypeSpec::Bool,
            optional: false,
        }],
        TypeSpec::Void,
    ),
    method(
        "process",
        "hasUncaughtExceptionCaptureCallback",
        false,
        None,
    ),
    method(
        "process",
        "setUncaughtExceptionCaptureCallback",
        false,
        None,
    ),
    method(
        "process",
        "addUncaughtExceptionCaptureCallback",
        false,
        None,
    ),
    method("process", "exit", false, None),
    method("process", "umask", false, None),
    method("process", "threadCpuUsage", false, None),
    method("process", "availableMemory", false, None),
    method("process", "constrainedMemory", false, None),
    method("process", "getuid", false, None),
    method("process", "geteuid", false, None),
    method("process", "getgid", false, None),
    method("process", "getegid", false, None),
    method("process", "getgroups", false, None),
    method("process", "setuid", false, None),
    method("process", "seteuid", false, None),
    method("process", "setgid", false, None),
    method("process", "setegid", false, None),
    method("process", "setgroups", false, None),
    method("process", "initgroups", false, None),
    method("process", "emitWarning", false, None),
    internal_method("process", "on", false, None),
    internal_method("process", "addListener", false, None),
    internal_method("process", "once", false, None),
    internal_method("process", "prependListener", false, None),
    internal_method("process", "prependOnceListener", false, None),
    internal_method("process", "emit", false, None),
    internal_method("process", "listeners", false, None),
    internal_method("process", "rawListeners", false, None),
    internal_method("process", "eventNames", false, None),
    internal_method("process", "listenerCount", false, None),
    internal_method("process", "removeListener", false, None),
    internal_method("process", "off", false, None),
    internal_method("process", "removeAllListeners", false, None),
    internal_method("process", "setMaxListeners", false, None),
    internal_method("process", "getMaxListeners", false, None),
    method("process", "cpuUsage", false, None),
    method("process", "resourceUsage", false, None),
    method("process", "getActiveResourcesInfo", false, None),
    method("process", "hrtime", false, None),
    property("process", "argv"),
    property("process", "platform"),
    property("process", "arch"),
    property("process", "pid"),
    property("process", "ppid"),
    property("process", "version"),
    property("process", "versions"),
    property("process", "stdin"),
    property("process", "stdout"),
    property("process", "stderr"),
    property("process", "env"),
    property("process", "allowedNodeEnvironmentFlags"),
    property("process", "argv0"),
    property("process", "config"),
    property("process", "debugPort"),
    property("process", "execArgv"),
    property("process", "execPath"),
    property("process", "features"),
    property("process", "finalization"),
    property("process", "moduleLoadList"),
    property("process", "permission"),
    property("process", "release"),
    property("process", "report"),
    property("process", "title"),
    // ===========================================================
    // Class exports (constructors `new Foo(...)` from a module).
    // ===========================================================
    class("buffer", "Buffer"),
    class("events", "EventEmitter"),
    class("events", "EventEmitterAsyncResource"),
    class("domain", "Domain"),
    class("ws", "WebSocketServer"),
    class("ws", "WebSocket"),
    class("net", "Socket"),
    class("net", "Stream"),
    class("net", "Server"),
    class("net", "BlockList"),
    class("net", "SocketAddress"),
    class("ioredis", "Redis"),
    class("mysql2/promise", "Pool"),
    class("mysql2", "Pool"),
    class("pg", "Pool"),
    class("pg", "Client"),
    class("url", "URL"),
    class("url", "URLSearchParams"),
    class("url", "URLPattern"),
    internal_method("url", "URLPattern", false, None),
    internal_method("url", "exec", true, Some("URLPattern")),
    internal_method("url", "test", true, Some("URLPattern")),
    // Issue #848: string_decoder.StringDecoder — handle-based dispatch
    // for `write` / `end` + `lastNeed` / `lastTotal` / `lastChar` getters.
    class("string_decoder", "StringDecoder"),
    method("string_decoder", "write", true, Some("StringDecoder")),
    method("string_decoder", "end", true, Some("StringDecoder")),
    internal_property("string_decoder", "lastNeed"),
    internal_property("string_decoder", "lastTotal"),
    internal_property("string_decoder", "lastChar"),
    internal_property("string_decoder", "encoding"),
    // node:querystring — legacy URL-encoded form parser. Greenfield
    // (deprecated since Node 11 but still imported by many npm pkgs).
    property("querystring", "default"),
    method("querystring", "escape", false, None),
    method("querystring", "unescape", false, None),
    method("querystring", "unescapeBuffer", false, None),
    method("querystring", "parse", false, None),
    method("querystring", "stringify", false, None),
    // `decode` / `encode` are aliases the test_parity_querystring fixture
    // verifies are *identity-equal* to parse/stringify. Native dispatch
    // routes both names to the same runtime symbol so the closures live
    // at the same address.
    method("querystring", "decode", false, None),
    method("querystring", "encode", false, None),
    // node:cluster — primary lifecycle surface. `setupPrimary` /
    // `setupMaster`, `fork`, and `disconnect` route through the native
    // module bound-method path. Workers share a listening port via
    // SO_REUSEPORT binds + a fork-IPC 'listening' round-trip (#4914);
    // `SCHED_RR` fd-passing and the shared ephemeral port for `listen(0)`
    // remain tracked in #4962.
    // #3687: default import (`import cluster from "node:cluster"`) is the
    // EventEmitter-shaped `cluster.default` namespace; the `import * as`
    // namespace keeps the shape-only surface.
    property("cluster", "default"),
    method("cluster", "fork", false, None),
    method("cluster", "disconnect", false, None),
    method("cluster", "setupPrimary", false, None),
    method("cluster", "setupMaster", false, None),
    class("cluster", "Worker"),
    property("cluster", "isPrimary"),
    property("cluster", "isMaster"),
    property("cluster", "isWorker"),
    internal_property("cluster", "worker"),
    property("cluster", "workers"),
    property("cluster", "settings"),
    property("cluster", "schedulingPolicy"),
    property("cluster", "SCHED_RR"),
    property("cluster", "SCHED_NONE"),
    // #3687: the EventEmitter method surface. On the `import * as` namespace
    // these all read `undefined` (they are not named exports); on the default
    // import they resolve to bound methods through `NATIVE_MODULE_TABLE`.
    internal_method("cluster", "on", false, None),
    internal_method("cluster", "addListener", false, None),
    internal_method("cluster", "once", false, None),
    internal_method("cluster", "prependListener", false, None),
    internal_method("cluster", "prependOnceListener", false, None),
    internal_method("cluster", "emit", false, None),
    internal_method("cluster", "eventNames", false, None),
    internal_method("cluster", "listenerCount", false, None),
    internal_method("cluster", "removeListener", false, None),
    internal_method("cluster", "off", false, None),
    internal_method("cluster", "removeAllListeners", false, None),
    // Keep property reads registered so the #463 strict gate accepts the
    // namespace-export shape; `get_native_module_constant` returns undefined
    // for these names at runtime.
    internal_property("cluster", "on"),
    internal_property("cluster", "addListener"),
    internal_property("cluster", "once"),
    internal_property("cluster", "prependListener"),
    internal_property("cluster", "prependOnceListener"),
    internal_property("cluster", "off"),
    internal_property("cluster", "removeListener"),
    internal_property("cluster", "removeAllListeners"),
    internal_property("cluster", "emit"),
    internal_property("cluster", "eventNames"),
    internal_property("cluster", "listenerCount"),
    // ===========================================================
    // #513 Phase A: backfill receiver-less surface for modules that
    // previously had zero entries. Without these, `module_has_any_entries`
    // returned false and the unimplemented-API gate (#463) silently
    // fell through to the old permissive behavior. One entry is enough
    // to flip strictness on for the module — the entries below cover
    // the most common surface so legitimate calls continue to compile.
    // ===========================================================

    // --- fs (sync surface lowered to Expr::Fs* in expr_call.rs;
    //     async + stream + extra sync helpers route through runtime
    //     externs declared by perry-runtime/src/fs.rs). ---
    method("fs", "_toUnixTimestamp", false, None),
    method("fs", "readFileSync", false, None),
    method("fs", "writeFileSync", false, None),
    method("fs", "appendFileSync", false, None),
    method("fs", "existsSync", false, None),
    method("fs", "exists", false, None),
    method("fs", "mkdirSync", false, None),
    method("fs", "unlinkSync", false, None),
    method("fs", "openSync", false, None),
    method("fs", "open", false, None),
    method("fs", "openAsBlob", false, None),
    method("fs", "closeSync", false, None),
    method("fs", "close", false, None),
    method("fs", "fstatSync", false, None),
    method("fs", "fstat", false, None),
    method("fs", "fsyncSync", false, None),
    method("fs", "fsync", false, None),
    method("fs", "fdatasyncSync", false, None),
    method("fs", "fdatasync", false, None),
    method("fs", "fchmodSync", false, None),
    method("fs", "fchmod", false, None),
    method("fs", "fchownSync", false, None),
    method("fs", "fchown", false, None),
    method("fs", "futimesSync", false, None),
    method("fs", "futimes", false, None),
    method("fs", "ftruncateSync", false, None),
    method("fs", "ftruncate", false, None),
    method("fs", "readSync", false, None),
    method("fs", "writeSync", false, None),
    method("fs", "read", false, None),
    method("fs", "write", false, None),
    method("fs", "readvSync", false, None),
    method("fs", "writevSync", false, None),
    method("fs", "readv", false, None),
    method("fs", "writev", false, None),
    method("fs", "rmSync", false, None),
    method("fs", "rmdirSync", false, None),
    method("fs", "readdirSync", false, None),
    method("fs", "statSync", false, None),
    method("fs", "lstat", false, None),
    method("fs", "statfsSync", false, None),
    method("fs", "statfs", false, None),
    method("fs", "opendirSync", false, None),
    method("fs", "opendir", false, None),
    method("fs", "globSync", false, None),
    method("fs", "glob", false, None),
    method("fs", "lstatSync", false, None),
    method("fs", "utimesSync", false, None),
    method("fs", "utimes", false, None),
    method("fs", "lutimesSync", false, None),
    method("fs", "lutimes", false, None),
    method("fs", "renameSync", false, None),
    method("fs", "copyFileSync", false, None),
    method("fs", "cpSync", false, None),
    method("fs", "cp", false, None),
    method("fs", "accessSync", false, None),
    method("fs", "realpathSync", false, None),
    method("fs", "realpath", false, None),
    method("fs", "mkdtempSync", false, None),
    method("fs", "mkdtempDisposableSync", false, None),
    method("fs", "mkdtemp", false, None),
    method("fs", "chmodSync", false, None),
    method("fs", "chmod", false, None),
    method("fs", "chownSync", false, None),
    method("fs", "chown", false, None),
    method("fs", "lchownSync", false, None),
    method("fs", "lchown", false, None),
    method("fs", "lchmodSync", false, None),
    method("fs", "lchmod", false, None),
    method("fs", "truncateSync", false, None),
    method("fs", "truncate", false, None),
    method("fs", "linkSync", false, None),
    method("fs", "link", false, None),
    method("fs", "symlinkSync", false, None),
    method("fs", "symlink", false, None),
    method("fs", "readlinkSync", false, None),
    method("fs", "readlink", false, None),
    method("fs", "readFile", false, None),
    method("fs", "writeFile", false, None),
    method("fs", "appendFile", false, None),
    method("fs", "access", false, None),
    method("fs", "rename", false, None),
    method("fs", "copyFile", false, None),
    method("fs", "mkdir", false, None),
    method("fs", "unlink", false, None),
    method("fs", "rm", false, None),
    method("fs", "rmdir", false, None),
    method("fs", "readdir", false, None),
    method("fs", "stat", false, None),
    method("fs", "createReadStream", false, None),
    method("fs", "createWriteStream", false, None),
    class("fs", "Dir"),
    class("fs", "Dirent"),
    class("fs", "Stats"),
    class("fs", "ReadStream"),
    class("fs", "WriteStream"),
    class("fs", "FileReadStream"),
    class("fs", "FileWriteStream"),
    class("fs", "Utf8Stream"),
    method("fs", "_toUnixTimestamp", false, None),
    method("fs", "watchFile", false, None),
    method("fs", "unwatchFile", false, None),
    method("fs", "watch", false, None),
    property("fs", "promises"),
    property("fs", "constants"),
    // --- node:diagnostics_channel direct submodule.
    property("diagnostics_channel", "default"),
    class("diagnostics_channel", "BoundedChannel"),
    class("diagnostics_channel", "Channel"),
    method("diagnostics_channel", "boundedChannel", false, None),
    method("diagnostics_channel", "channel", false, None),
    method("diagnostics_channel", "hasSubscribers", false, None),
    method("diagnostics_channel", "subscribe", false, None),
    method("diagnostics_channel", "tracingChannel", false, None),
    method("diagnostics_channel", "unsubscribe", false, None),
    // --- node:fs/promises direct submodule (#2728). Only the named exports
    // Perry actually backs with runtime thunks (see
    // `perry-runtime::node_submodules::fs_promises`) are declared. FileHandle
    // receiver-only methods are represented with class filters when runtime
    // backed; the parent `fs.promises` namespace above still resolves to the
    // same surface.
    property("fs/promises", "default"),
    property("fs/promises", "constants"),
    method("fs/promises", "access", false, None),
    method("fs/promises", "appendFile", false, None),
    method("fs/promises", "chmod", false, None),
    method("fs/promises", "chown", false, None),
    method("fs/promises", "copyFile", false, None),
    method("fs/promises", "cp", false, None),
    method("fs/promises", "glob", false, None),
    method("fs/promises", "lchmod", false, None),
    method("fs/promises", "lchown", false, None),
    method("fs/promises", "link", false, None),
    method("fs/promises", "lstat", false, None),
    method("fs/promises", "lutimes", false, None),
    method("fs/promises", "mkdir", false, None),
    method("fs/promises", "mkdtemp", false, None),
    method("fs/promises", "mkdtempDisposable", false, None),
    method("fs/promises", "open", false, None),
    method("fs/promises", "opendir", false, None),
    method("fs/promises", "readFile", false, None),
    method("fs/promises", "readdir", false, None),
    method("fs/promises", "readlink", false, None),
    method("fs/promises", "realpath", false, None),
    method("fs/promises", "rename", false, None),
    method("fs/promises", "rm", false, None),
    method("fs/promises", "rmdir", false, None),
    method("fs/promises", "stat", false, None),
    method("fs/promises", "statfs", false, None),
    method("fs/promises", "symlink", false, None),
    method("fs/promises", "truncate", false, None),
    method("fs/promises", "unlink", false, None),
    method("fs/promises", "utimes", false, None),
    method("fs/promises", "watch", false, None),
    method("fs/promises", "writeFile", false, None),
    method("fs/promises", "pull", true, Some("FileHandle")),
    method("fs/promises", "pullSync", true, Some("FileHandle")),
    method("fs/promises", "writer", true, Some("FileHandle")),
    // --- console (Node global console exposed as node:console too). ---
    class("console", "Console"),
    method("console", "log", false, None),
    method("console", "info", false, None),
    method("console", "debug", false, None),
    method("console", "error", false, None),
    method("console", "warn", false, None),
    method("console", "assert", false, None),
    method("console", "dir", false, None),
    method("console", "dirxml", false, None),
    method("console", "trace", false, None),
    method("console", "table", false, None),
    method("console", "clear", false, None),
    method("console", "count", false, None),
    method("console", "countReset", false, None),
    method("console", "time", false, None),
    method("console", "timeEnd", false, None),
    method("console", "timeLog", false, None),
    method("console", "group", false, None),
    method("console", "groupCollapsed", false, None),
    method("console", "groupEnd", false, None),
    method("console", "profile", false, None),
    method("console", "profileEnd", false, None),
    method("console", "timeStamp", false, None),
    method("console", "context", false, None),
    method("console", "createTask", false, None),
    // --- util (a small surface — Perry implements util.inspect /
    //     util.format / util.promisify shapes through builtins.rs;
    //     the rest are documented stubs) ---
    property("util", "default"),
    method("util", "inspect", false, None),
    method("util", "format", false, None),
    method("util", "convertProcessSignalToExitCode", false, None),
    method("util", "debug", false, None),
    method("util", "diff", false, None),
    // #2514: libuv-style errno helpers.
    method("util", "getSystemErrorName", false, None),
    method("util", "getSystemErrorMessage", false, None),
    method("util", "getSystemErrorMap", false, None),
    method("util", "aborted", false, None),
    method("util", "transferableAbortController", false, None),
    method("util", "transferableAbortSignal", false, None),
    method("util", "getCallSites", false, None),
    method("util", "parseEnv", false, None),
    // #2514: util.toUSVString(value) → string with lone surrogates replaced.
    method("util", "toUSVString", false, None),
    method("util", "setTraceSigInt", false, None),
    // `util.formatWithOptions(options, format[, ...args])` — identical to
    // `util.format` except the first arg is an `util.inspect` options bag
    // applied to any `%o`/`%O` placeholders. Required by the `debug` npm
    // package (top-1k downloads, transitive dep of express/socket.io). Our
    // stub ignores the options bag and delegates to `util.format`; full
    // options-passthrough is a follow-up.
    method("util", "formatWithOptions", false, None),
    method("util", "promisify", false, None),
    method("util", "callbackify", false, None),
    method("util", "debuglog", false, None),
    method("util", "_extend", false, None),
    method("util", "_errnoException", false, None),
    method("util", "_exceptionWithHostPort", false, None),
    method("util", "deprecate", false, None),
    method("util", "inherits", false, None),
    method_sig(
        "util",
        "isArray",
        false,
        None,
        &[p_any("value")],
        TypeSpec::Bool,
    ),
    method("util", "isDeepStrictEqual", false, None),
    method("util", "parseArgs", false, None),
    method("util", "stripVTControlCharacters", false, None),
    method("util", "styleText", false, None),
    // MIMEType/MIMEParams are exposed both as classes (for `new`) and as
    // bare-call native dispatch rows in NODE_CORE_ROWS; the method twin
    // satisfies the dispatch-counterpart drift guard.
    method("util", "MIMEType", false, None),
    method("util", "MIMEParams", false, None),
    class("util", "MIMEType"),
    class("util", "MIMEParams"),
    class("util", "TextEncoder"),
    class("util", "TextDecoder"),
    // util.types — Node's runtime type-introspection namespace. The
    // direct `node:util/types` import form and the `util.types` namespace
    // access form both lower to this canonical module key.
    property("util", "types"),
    method("util/types", "isArgumentsObject", false, None),
    method("util/types", "isPromise", false, None),
    method("util/types", "isBigIntObject", false, None),
    method("util/types", "isArrayBuffer", false, None),
    method("util/types", "isSharedArrayBuffer", false, None),
    method("util/types", "isAnyArrayBuffer", false, None),
    method("util/types", "isArrayBufferView", false, None),
    method("util/types", "isDataView", false, None),
    method("util/types", "isTypedArray", false, None),
    method("util/types", "isUint8Array", false, None),
    method("util/types", "isInt8Array", false, None),
    method("util/types", "isInt16Array", false, None),
    method("util/types", "isUint16Array", false, None),
    method("util/types", "isInt32Array", false, None),
    method("util/types", "isUint32Array", false, None),
    method("util/types", "isFloat16Array", false, None),
    method("util/types", "isFloat32Array", false, None),
    method("util/types", "isFloat64Array", false, None),
    method("util/types", "isUint8ClampedArray", false, None),
    method("util/types", "isBigInt64Array", false, None),
    method("util/types", "isBigUint64Array", false, None),
    method("util/types", "isMap", false, None),
    method("util/types", "isMapIterator", false, None),
    method("util/types", "isProxy", false, None),
    method("util/types", "isExternal", false, None),
    method("util/types", "isModuleNamespaceObject", false, None),
    method("util/types", "isSet", false, None),
    method("util/types", "isSetIterator", false, None),
    method("util/types", "isWeakMap", false, None),
    method("util/types", "isWeakSet", false, None),
    method("util/types", "isDate", false, None),
    method("util/types", "isRegExp", false, None),
    method("util/types", "isAsyncFunction", false, None),
    method("util/types", "isGeneratorFunction", false, None),
    method("util/types", "isGeneratorObject", false, None),
    method("util/types", "isNativeError", false, None),
    method("util/types", "isKeyObject", false, None),
    method("util/types", "isCryptoKey", false, None),
    // Boxed primitive introspection (PR #1257). The `util/types` import form
    // and the `util.types` namespace-access form both lower to this canonical
    // module key.
    method("util/types", "isNumberObject", false, None),
    method("util/types", "isStringObject", false, None),
    method("util/types", "isBooleanObject", false, None),
    method("util/types", "isSymbolObject", false, None),
    method("util/types", "isBoxedPrimitive", false, None),
    // --- sys: deprecated alias for node:util. Keep this module-level
    // surface aligned with the public `util` manifest rows above; the
    // runtime routes `node:sys` through the util namespace.
    property("sys", "default"),
    method("sys", "inspect", false, None),
    method("sys", "format", false, None),
    method("sys", "convertProcessSignalToExitCode", false, None),
    method("sys", "debug", false, None),
    method("sys", "diff", false, None),
    method("sys", "getSystemErrorName", false, None),
    method("sys", "getSystemErrorMessage", false, None),
    method("sys", "getSystemErrorMap", false, None),
    method("sys", "aborted", false, None),
    method("sys", "transferableAbortController", false, None),
    method("sys", "transferableAbortSignal", false, None),
    method("sys", "getCallSites", false, None),
    method("sys", "parseEnv", false, None),
    method("sys", "formatWithOptions", false, None),
    method("sys", "promisify", false, None),
    method("sys", "callbackify", false, None),
    method("sys", "debuglog", false, None),
    method("sys", "_extend", false, None),
    method("sys", "_errnoException", false, None),
    method("sys", "_exceptionWithHostPort", false, None),
    method("sys", "deprecate", false, None),
    method("sys", "inherits", false, None),
    method_sig(
        "sys",
        "isArray",
        false,
        None,
        &[p_any("value")],
        TypeSpec::Bool,
    ),
    method("sys", "isDeepStrictEqual", false, None),
    method("sys", "parseArgs", false, None),
    method("sys", "stripVTControlCharacters", false, None),
    method("sys", "styleText", false, None),
    method("sys", "toUSVString", false, None),
    method("sys", "setTraceSigInt", false, None),
    method("sys", "MIMEType", false, None),
    method("sys", "MIMEParams", false, None),
    class("sys", "MIMEType"),
    class("sys", "MIMEParams"),
    class("sys", "TextEncoder"),
    class("sys", "TextDecoder"),
    property("sys", "types"),
    // node:assert — assertion helpers used by tests and many npm packages.
    method("assert", "ok", false, None),
    method("assert", "fail", false, None),
    method("assert", "equal", false, None),
    method("assert", "notEqual", false, None),
    method("assert", "strictEqual", false, None),
    method("assert", "notStrictEqual", false, None),
    method("assert", "deepEqual", false, None),
    method("assert", "notDeepEqual", false, None),
    method("assert", "deepStrictEqual", false, None),
    method("assert", "partialDeepStrictEqual", false, None),
    method("assert", "notDeepStrictEqual", false, None),
    method("assert", "match", false, None),
    method("assert", "doesNotMatch", false, None),
    method("assert", "throws", false, None),
    method("assert", "doesNotThrow", false, None),
    method("assert", "rejects", false, None),
    method("assert", "doesNotReject", false, None),
    method("assert", "ifError", false, None),
    method("assert", "default", false, None),
    method("assert", "strict", false, None),
    property("assert", "strict"),
    class("assert", "Assert"),
    class("assert", "AssertionError"),
    method("assert/strict", "ok", false, None),
    method("assert/strict", "fail", false, None),
    method("assert/strict", "equal", false, None),
    method("assert/strict", "notEqual", false, None),
    method("assert/strict", "strictEqual", false, None),
    method("assert/strict", "notStrictEqual", false, None),
    method("assert/strict", "deepEqual", false, None),
    method("assert/strict", "notDeepEqual", false, None),
    method("assert/strict", "deepStrictEqual", false, None),
    method("assert/strict", "partialDeepStrictEqual", false, None),
    method("assert/strict", "notDeepStrictEqual", false, None),
    method("assert/strict", "match", false, None),
    method("assert/strict", "doesNotMatch", false, None),
    method("assert/strict", "throws", false, None),
    method("assert/strict", "doesNotThrow", false, None),
    method("assert/strict", "rejects", false, None),
    method("assert/strict", "doesNotReject", false, None),
    method("assert/strict", "ifError", false, None),
    method("assert/strict", "default", false, None),
    method("assert/strict", "strict", false, None),
    property("assert/strict", "strict"),
    class("assert/strict", "Assert"),
    class("assert/strict", "AssertionError"),
    property("dns", "ADDRCONFIG"),
    property("dns", "V4MAPPED"),
    property("dns", "ALL"),
    property("dns", "NODATA"),
    property("dns", "FORMERR"),
    property("dns", "SERVFAIL"),
    property("dns", "NOTFOUND"),
    property("dns", "NOTIMP"),
    property("dns", "REFUSED"),
    property("dns", "BADQUERY"),
    property("dns", "BADNAME"),
    property("dns", "BADFAMILY"),
    property("dns", "BADRESP"),
    property("dns", "CONNREFUSED"),
    property("dns", "TIMEOUT"),
    property("dns", "EOF"),
    property("dns", "FILE"),
    property("dns", "NOMEM"),
    property("dns", "DESTRUCTION"),
    property("dns", "BADSTR"),
    property("dns", "BADFLAGS"),
    property("dns", "NONAME"),
    property("dns", "BADHINTS"),
    property("dns", "NOTINITIALIZED"),
    property("dns", "LOADIPHLPAPI"),
    property("dns", "ADDRGETNETWORKPARAMS"),
    property("dns", "CANCELLED"),
    property("dns", "default"),
    property("dns", "promises"),
    property("dns/promises", "default"),
    property("dns/promises", "NODATA"),
    property("dns/promises", "FORMERR"),
    property("dns/promises", "SERVFAIL"),
    property("dns/promises", "NOTFOUND"),
    property("dns/promises", "NOTIMP"),
    property("dns/promises", "REFUSED"),
    property("dns/promises", "BADQUERY"),
    property("dns/promises", "BADNAME"),
    property("dns/promises", "BADFAMILY"),
    property("dns/promises", "BADRESP"),
    property("dns/promises", "CONNREFUSED"),
    property("dns/promises", "TIMEOUT"),
    property("dns/promises", "EOF"),
    property("dns/promises", "FILE"),
    property("dns/promises", "NOMEM"),
    property("dns/promises", "DESTRUCTION"),
    property("dns/promises", "BADSTR"),
    property("dns/promises", "BADFLAGS"),
    property("dns/promises", "NONAME"),
    property("dns/promises", "BADHINTS"),
    property("dns/promises", "NOTINITIALIZED"),
    property("dns/promises", "LOADIPHLPAPI"),
    property("dns/promises", "ADDRGETNETWORKPARAMS"),
    property("dns/promises", "CANCELLED"),
    // --- stream (Web Streams API + Node stream classes — see
    //     perry-stdlib/src/streams.rs and perry-ext-streams) ---
    class("stream", "Readable"),
    class("stream", "Writable"),
    class("stream", "Duplex"),
    class("stream", "Transform"),
    class("stream", "PassThrough"),
    // Legacy base class (extends EventEmitter); modern classes hang off it as
    // statics. `stream.Stream === stream.default`. #1966.
    class("stream", "Stream"),
    // `node:stream`'s default export is the legacy `Stream` class itself.
    method("stream", "default", false, None),
    method("stream", "pipeline", false, None),
    method("stream", "finished", false, None),
    property("stream", "promises"),
    method("stream/promises", "pipeline", false, None),
    method("stream/promises", "finished", false, None),
    // Direct `node:stream/consumers` submodule exports.
    property("stream/consumers", "default"),
    method("stream/consumers", "arrayBuffer", false, None),
    method("stream/consumers", "blob", false, None),
    method("stream/consumers", "buffer", false, None),
    method("stream/consumers", "bytes", false, None),
    method("stream/consumers", "json", false, None),
    method("stream/consumers", "text", false, None),
    // Direct `node:stream/web` submodule exports. The constructors are backed
    // by Perry's Web Streams runtime; remaining semantic gaps stay tracked by
    // the stream/web parity issues.
    property("stream/web", "default"),
    class("stream/web", "ReadableStream"),
    class("stream/web", "ReadableStreamDefaultReader"),
    // #4915: BYOB readers are real — `new ReadableStreamBYOBReader(stream)` /
    // `getReader({ mode: "byob" })` mint a reader whose `read(view)` fills the
    // caller-supplied buffer; the byte-stream controller's `byobRequest`
    // exposes `view` / `respond(bytesWritten)` / `respondWithNewView(view)`.
    class("stream/web", "ReadableStreamBYOBReader"),
    class("stream/web", "ReadableStreamBYOBRequest"),
    class("stream/web", "ReadableByteStreamController"),
    class("stream/web", "ReadableStreamDefaultController"),
    class("stream/web", "TransformStream"),
    class("stream/web", "TransformStreamDefaultController"),
    class("stream/web", "WritableStream"),
    class("stream/web", "WritableStreamDefaultWriter"),
    class("stream/web", "WritableStreamDefaultController"),
    // #4915: real byteLength accounting — per-chunk size() results are summed
    // into desiredSize for ReadableStream/WritableStream/TransformStream.
    class("stream/web", "ByteLengthQueuingStrategy"),
    class("stream/web", "CountQueuingStrategy"),
    class("stream/web", "TextEncoderStream"),
    class("stream/web", "TextDecoderStream"),
    class("stream/web", "CompressionStream"),
    class("stream/web", "DecompressionStream"),
    // `require('stream')` returns the legacy `Stream` constructor itself,
    // which has its own `.prototype` (it extends EventEmitter). The
    // `node_modules/send` package (express's static-file backend) does
    // `util.inherits(SendStream, require('stream'))`, which reads
    // `Stream.prototype` — the gate rejects the access without this entry.
    internal_property("stream", "prototype"),
    // #1533: `stream.promises` namespace (`await pipeline(...)` /
    // `finished(...)`). The read resolves to a `stream/promises`-tagged
    // namespace object; its members are gated under that submodule name.
    property("stream", "promises"),
    method("stream/promises", "pipeline", false, None),
    method("stream/promises", "finished", false, None),
    // `Readable.from(iterable)` — Node's static factory. Resolves
    // through the `Readable.foo` -> `stream.foo` route in
    // `lower_call.rs`, so the gate keys off `stream.from`.
    internal_method("stream", "from", false, None),
    // #1534/#1746: static introspection helpers — `Readable.isDisturbed(s)`,
    // `Readable.isErrored(s)`, `Readable.isReadable(s)`, and
    // `stream.isWritable(s)` (also re-exported module-level). Perry tracks
    // per-stream disturbed/errored bits and readable/writable direction
    // flags, so these answer per-instance (`null` for the wrong direction,
    // `false` once ended/errored, `true` otherwise).
    method("stream", "isDisturbed", false, None),
    method("stream", "isErrored", false, None),
    method("stream", "isReadable", false, None),
    method("stream", "isWritable", false, None),
    // #2685: Node exposes these byte-view helpers and destroyed-state
    // predicate directly from `node:stream`.
    method("stream", "_isArrayBufferView", false, None),
    method("stream", "_isUint8Array", false, None),
    method("stream", "_uint8ArrayToBuffer", false, None),
    method("stream", "isDestroyed", false, None),
    // #1537: `stream.getDefaultHighWaterMark(objectMode)` /
    // `setDefaultHighWaterMark(objectMode, value)` — the per-mode platform
    // default highWaterMark (65536 byte / 16 objectMode), mutable at runtime.
    method("stream", "getDefaultHighWaterMark", false, None),
    method("stream", "setDefaultHighWaterMark", false, None),
    // #1541: `stream.addAbortSignal(signal, stream)` — Node wires
    // the AbortSignal so aborting it destroys the stream. Stub
    // ignores the signal and returns the stream verbatim so chain
    // patterns (`r = addAbortSignal(s, r)`) keep working.
    method("stream", "addAbortSignal", false, None),
    // #1539: `stream.compose(...streams)` chains streams into a
    // composite Duplex; `stream.duplexPair([opts])` returns a paired
    // `[Duplex, Duplex]`. Both return fresh Duplex stubs today.
    method("stream", "compose", false, None),
    method("stream", "duplexPair", false, None),
    // #1540: Web-stream interop helpers — Readable/Writable .toWeb /
    // .fromWeb. Stubs return a fresh Duplex (data isn't propagated
    // between Node and WHATWG universes yet).
    internal_method("stream", "toWeb", false, None),
    internal_method("stream", "fromWeb", false, None),
    // EventEmitter methods on stream instances. node:stream extends
    // EventEmitter — every Readable/Writable/Duplex/Transform/PassThrough
    // exposes the full `.on('data'|'end'|'error'|'close'|...)` /
    // `.once` / `.off` / `.removeListener` / `.emit` /
    // `.removeAllListeners` / `.addListener` / `.prependListener` /
    // `.prependOnceListener` / `.listenerCount` / `.listeners` /
    // `.eventNames` / `.setMaxListeners` / `.getMaxListeners` surface.
    // The runtime closures are built by `js_node_stream_*_new` (see
    // `crates/perry-runtime/src/node_stream.rs`); these entries exist so
    // the #463 unimplemented-API gate accepts `stream.on(...)` /
    // `stream.once(...)` / etc. in user code (e.g. axios's
    // `AxiosTransformStream extends stream.Transform` + downstream
    // event wiring). Has_receiver=true because every call site reads
    // `<instance>.on(...)`, not `stream.on(...)` as a module-level
    // helper.
    method("stream", "on", true, None),
    method("stream", "once", true, None),
    method("stream", "off", true, None),
    method("stream", "addListener", true, None),
    method("stream", "removeListener", true, None),
    method("stream", "removeAllListeners", true, None),
    method("stream", "emit", true, None),
    method("stream", "prependListener", true, None),
    method("stream", "prependOnceListener", true, None),
    method("stream", "listenerCount", true, None),
    method("stream", "listeners", true, None),
    method("stream", "rawListeners", true, None),
    method("stream", "eventNames", true, None),
    method("stream", "setMaxListeners", true, None),
    method("stream", "getMaxListeners", true, None),
    // Core stream instance stubs used by stream/promises and the
    // Readable/Writable/Duplex/Transform/PassThrough constructor surface.
    method("stream", "read", true, None),
    method("stream", "pipe", true, None),
    method("stream", "unpipe", true, None),
    method("stream", "pause", true, None),
    method("stream", "resume", true, None),
    method("stream", "isPaused", true, None),
    method("stream", "destroy", true, None),
    method("stream", "setEncoding", true, None),
    method("stream", "write", true, None),
    method("stream", "end", true, None),
    method("stream", "cork", true, None),
    method("stream", "uncork", true, None),
    // #1539: push() backpressure return + readable/writableHighWaterMark
    // property getters on typed stream instances.
    method("stream", "push", true, None),
    method("stream", "unshift", true, None),
    method("stream", "readableFlowing", true, None),
    method("stream", "readableHighWaterMark", true, None),
    method("stream", "readableLength", true, None),
    method("stream", "readableObjectMode", true, None),
    method("stream", "readable", true, None),
    method("stream", "readableEnded", true, None),
    method("stream", "readableEncoding", true, None),
    method("stream", "writableHighWaterMark", true, None),
    method("stream", "writableLength", true, None),
    method("stream", "writableNeedDrain", true, None),
    method("stream", "writableObjectMode", true, None),
    method("stream", "readableAborted", true, None),
    method("stream", "closed", true, None),
    method("stream", "errored", true, None),
    method("stream", "readableDidRead", true, None),
    method("stream", "writableCorked", true, None),
    method("stream", "writable", true, None),
    method("stream", "writableEnded", true, None),
    method("stream", "writableFinished", true, None),
    method("stream", "allowHalfOpen", true, None),
    method("stream", "destroyed", true, None),
    // --- child_process (synchronous + async exec surface;
    //     spawn/fork are documented but not yet codegen'd) ---
    method("child_process", "_forkChild", false, None),
    method("child_process", "exec", false, None),
    method("child_process", "execSync", false, None),
    method("child_process", "execFile", false, None),
    method("child_process", "execFileSync", false, None),
    method("child_process", "spawn", false, None),
    method("child_process", "spawnSync", false, None),
    method("child_process", "fork", false, None),
    property("child_process", "default"),
    // #1856: `ChildProcess` is the streaming-subprocess constructor; reading
    // it as a value yields `[Function: ChildProcess]`. `Stream` is not a real
    // `child_process` export (Node returns `undefined`) — registered so the
    // value-read passes the #463 surface gate and resolves to `undefined`.
    class("child_process", "ChildProcess"),
    internal_property("child_process", "Stream"),
    // --- node-pty (#6563: runtime-native pty; `spawn` is the whole module
    //     surface — the IPty methods live on the returned object). The
    //     @lydell fork is API-identical; both rows exist so either import
    //     name passes the #463 surface gate. ---
    method("node-pty", "spawn", false, None),
    property("node-pty", "default"),
    method("@lydell/node-pty", "spawn", false, None),
    property("@lydell/node-pty", "default"),
    // --- tty ---
    method("tty", "isatty", false, None),
    class("tty", "ReadStream"),
    class("tty", "WriteStream"),
    // Constructor-style factory dispatch (`tty.ReadStream(fd)` /
    // `tty.WriteStream(fd)`) — `has_receiver: false` rows in
    // NATIVE_MODULE_TABLE need a matching Method entry so the
    // dispatch->manifest drift guard (manifest_consistency.rs) passes.
    method("tty", "ReadStream", false, None),
    method("tty", "WriteStream", false, None),
    method("tty", "setRawMode", true, Some("ReadStream")),
    method("tty", "getColorDepth", true, Some("WriteStream")),
    method("tty", "hasColors", true, Some("WriteStream")),
    method("tty", "_refreshSize", true, Some("WriteStream")),
    method("tty", "cursorTo", true, Some("WriteStream")),
    method("tty", "moveCursor", true, Some("WriteStream")),
    method("tty", "clearLine", true, Some("WriteStream")),
    method("tty", "clearScreenDown", true, Some("WriteStream")),
    method("tty", "getWindowSize", true, Some("WriteStream")),
    method("tty", "on", true, Some("WriteStream")),
    method("tty", "addListener", true, Some("WriteStream")),
    method("tty", "once", true, Some("WriteStream")),
    method("tty", "removeListener", true, Some("WriteStream")),
    method("tty", "off", true, Some("WriteStream")),
    method("tty", "removeAllListeners", true, Some("WriteStream")),
    // --- wasi ---
    class("wasi", "WASI"),
    method("wasi", "WASI", false, None),
    method("wasi", "getImportObject", true, Some("WASI")),
    method("wasi", "start", true, Some("WASI")),
    method("wasi", "initialize", true, Some("WASI")),
    method("wasi", "finalizeBindings", true, Some("WASI")),
    property("wasi", "wasiImport"),
    // --- node:vm ---
    method_sig(
        "vm",
        "createContext",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    // --- node:repl ---
    property("repl", "default"),
    property("repl", "builtinModules"),
    property("repl", "REPL_MODE_SLOPPY"),
    property("repl", "REPL_MODE_STRICT"),
    class("repl", "REPLServer"),
    class("repl", "Recoverable"),
    method("repl", "start", false, None).stub_note(
        "REPLServer shape only: never reads the input stream, and .write() evaluates just numeric literals, context lookups, and a single '+'; no real JS eval loop (#4916)",
    ),
    method("repl", "REPLServer", false, None).stub_note(
        "REPLServer shape only: never reads the input stream, and .write() evaluates just numeric literals, context lookups, and a single '+'; no real JS eval loop (#4916)",
    ),
    method("repl", "Recoverable", false, None),
    internal_method("repl", "on", true, Some("REPLServer")),
    internal_method("repl", "addListener", true, Some("REPLServer")),
    internal_method("repl", "once", true, Some("REPLServer")),
    internal_method("repl", "emit", true, Some("REPLServer")),
    internal_method("repl", "write", true, Some("REPLServer")),
    internal_method("repl", "defineCommand", true, Some("REPLServer")),
    internal_method("repl", "displayPrompt", true, Some("REPLServer")),
    internal_method("repl", "clearBufferedCommand", true, Some("REPLServer")),
    internal_method("repl", "setupHistory", true, Some("REPLServer")),
    // --- perf_hooks (W3C User Timing on `performance` + PerformanceObserver) ---
    internal_method("perf_hooks", "now", false, None),
    internal_method("perf_hooks", "mark", false, None),
    internal_method("perf_hooks", "measure", false, None),
    internal_method("perf_hooks", "getEntries", false, None),
    internal_method("perf_hooks", "getEntriesByName", false, None),
    internal_method("perf_hooks", "getEntriesByType", false, None),
    internal_method("perf_hooks", "clearMarks", false, None),
    internal_method("perf_hooks", "clearMeasures", false, None),
    internal_method("perf_hooks", "eventLoopUtilization", false, None),
    internal_method("perf_hooks", "toJSON", false, None),
    internal_method("perf_hooks", "clearResourceTimings", false, None),
    internal_method("perf_hooks", "setResourceTimingBufferSize", false, None),
    // Resource timing entries are recorded through the perf_hooks timeline.
    internal_method("perf_hooks", "markResourceTiming", false, None),
    // timerify returns a wrapper that emits observer-visible function entries.
    method("perf_hooks", "timerify", false, None),
    // #1336: monitorEventLoopDelay() / createHistogram() return a
    // Histogram-shaped object whose method/property reads route
    // through the internal `perf_histogram` namespace (not listed in
    // NATIVE_MODULES because users never import it — they receive the
    // object as a return value, same pattern as `perf_observer`).
    // Stub — every stat reads 0 and the mutators are no-ops.
    method("perf_hooks", "monitorEventLoopDelay", false, None),
    method("perf_hooks", "createHistogram", false, None),
    internal_property("perf_hooks", "timeOrigin"),
    internal_property("perf_hooks", "nodeTiming"),
    property("perf_hooks", "performance"),
    property("perf_hooks", "constants"),
    class("perf_hooks", "Performance"),
    class("perf_hooks", "PerformanceObserver"),
    // PerformanceObserver.supportedEntryTypes — static array of entry-type
    // names. Read inline (`PerformanceObserver.supportedEntryTypes.includes(...)`)
    // it resolves as a perf_hooks property; declare it so the read isn't gated.
    internal_property("perf_hooks", "supportedEntryTypes"),
    class("perf_hooks", "PerformanceEntry"),
    class("perf_hooks", "PerformanceMark"),
    class("perf_hooks", "PerformanceMeasure"),
    class("perf_hooks", "PerformanceObserverEntryList"),
    class("perf_hooks", "PerformanceResourceTiming"),
    method("perf_hooks", "observe", true, Some("PerformanceObserver")),
    method(
        "perf_hooks",
        "disconnect",
        true,
        Some("PerformanceObserver"),
    ),
    method(
        "perf_hooks",
        "takeRecords",
        true,
        Some("PerformanceObserver"),
    ),
    // --- node:v8 (#3137/#3138/#3142) ---
    method("v8", "serialize", false, None),
    method("v8", "deserialize", false, None),
    method("v8", "getHeapStatistics", false, None).stub_note(
        "Node shape, Perry numbers: total_heap_size/used_heap_size/malloced_memory/total_allocated_bytes from Perry arenas, total_physical_size=RSS, heap_size_limit fixed ~2GB (not enforced); *_executable, external_memory, global-handles and zap fields are 0 (#4916)",
    ),
    method("v8", "getHeapCodeStatistics", false, None)
        .stub_note("all fields 0; Perry compiles AOT, there is no JIT code heap (#4916)"),
    method("v8", "getHeapSpaceStatistics", false, None).stub_note(
        "Node space names with all live usage attributed to old_space from Perry arenas; other spaces report 0 (#4916)",
    ),
];
