//! `API_MANIFEST` entries, part 1. Split out of entries.rs to satisfy the
//! 2000-line file-size gate; concatenated at compile time by the parent.
//!
//! `use super::*` pulls in the parent's type imports and the const-fn entry
//! builders (`method`/`property`/`class`/…) — children can name an ancestor's
//! private items, so the builders need no visibility change.

use super::*;

pub(crate) const API_MANIFEST_PART_1: &[ApiEntry] = &[
    // ===========================================================
    // Methods dispatched via NATIVE_MODULE_TABLE
    // (extracted from crates/perry-codegen/src/lower_call.rs;
    //  drift guarded by perry-codegen's manifest_consistency test)
    // ===========================================================
    method_sig(
        "fastify",
        "default",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method("fastify", "get", true, None),
    method("fastify", "post", true, None),
    method("fastify", "put", true, None),
    method("fastify", "delete", true, None),
    method("fastify", "patch", true, None),
    method("fastify", "head", true, None),
    method("fastify", "options", true, None),
    method("fastify", "all", true, None),
    method("fastify", "route", true, None),
    method("fastify", "addHook", true, None),
    method("fastify", "setErrorHandler", true, None),
    method("fastify", "register", true, None),
    method("fastify", "listen", true, None),
    method("fastify", "close", true, None),
    // #1113 — `app.server` is a Node-compatible getter returning the
    // FastifyApp handle (pointer-tagged) so `typeof app.server ===
    // "object"`. Lowered as a zero-arg NativeMethodCall by the HIR
    // property-as-method path; the runtime side is
    // `js_fastify_app_server`. `app.server.on(event, cb)` then
    // dispatches against the same handle (the `"on"` arm below).
    // Today only `"upgrade"` is stored; bidirectional WebSocket
    // upgrade through hyper is the tracked follow-up.
    method("fastify", "server", true, None),
    method("fastify", "on", true, None),
    method("fastify", "method", true, None),
    method("fastify", "url", true, None),
    // Manifest-consistency catch-up (release-sweep gate).
    method("fastify", "type", true, None),
    method("fastify", "params", true, None),
    method("fastify", "param", true, None),
    method("fastify", "query", true, None),
    method("fastify", "rawBody", true, None),
    method("fastify", "headers", true, None),
    method("fastify", "header", true, None),
    method("fastify", "user", true, None),
    method("fastify", "status", true, None),
    method("fastify", "code", true, None),
    method("fastify", "send", true, None),
    method("fastify", "text", true, None),
    method("fastify", "html", true, None),
    method("fastify", "redirect", true, None),
    method("fastify", "json", true, None),
    method("fastify", "body", true, None),
    method_sig(
        "mysql2",
        "createConnection",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method_sig(
        "mysql2",
        "createPool",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method_sig(
        "mysql2/promise",
        "createConnection",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method_sig(
        "mysql2/promise",
        "createPool",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method("mysql2", "query", true, Some("Pool")),
    method("mysql2", "execute", true, Some("Pool")),
    method("mysql2", "end", true, Some("Pool")),
    method("mysql2/promise", "query", true, Some("Pool")),
    method("mysql2/promise", "execute", true, Some("Pool")),
    method("mysql2/promise", "end", true, Some("Pool")),
    method("mysql2", "query", true, Some("PoolConnection")),
    method("mysql2", "execute", true, Some("PoolConnection")),
    method("mysql2/promise", "query", true, Some("PoolConnection")),
    method("mysql2/promise", "execute", true, Some("PoolConnection")),
    method("mysql2", "query", true, None),
    method("mysql2", "execute", true, None),
    method("mysql2", "end", true, None),
    method("mysql2", "getConnection", true, None),
    method("mysql2", "release", true, None),
    method("mysql2", "beginTransaction", true, None),
    method("mysql2", "commit", true, None),
    method("mysql2", "rollback", true, None),
    method("mysql2/promise", "query", true, None),
    method("mysql2/promise", "execute", true, None),
    method("mysql2/promise", "end", true, None),
    method("mysql2/promise", "getConnection", true, None),
    method("mysql2/promise", "release", true, None),
    method("mysql2/promise", "beginTransaction", true, None),
    method("mysql2/promise", "commit", true, None),
    method("mysql2/promise", "rollback", true, None),
    method_sig("pg", "connect", false, None, &[p_any("p0")], TypeSpec::Any),
    method_sig("pg", "Pool", false, None, &[p_any("p0")], TypeSpec::Any),
    method("pg", "connect", true, Some("Client")),
    method("pg", "query", true, Some("Pool")),
    method("pg", "end", true, Some("Pool")),
    method("pg", "query", true, None),
    method("pg", "end", true, None),
    method_sig(
        "ioredis",
        "createClient",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method("ioredis", "set", true, None),
    method("ioredis", "get", true, None),
    method("ioredis", "del", true, None),
    method("ioredis", "exists", true, None),
    method("ioredis", "incr", true, None),
    method("ioredis", "decr", true, None),
    method("ioredis", "expire", true, None),
    method("ioredis", "quit", true, None),
    // v0.5.707 closes-#605: NATIVE_MODULE_TABLE added connect/disconnect rows
    // when normalizing the `redis` npm package alias to ioredis dispatch.
    // Manifest must mirror or `every_dispatch_entry_has_manifest_counterpart`
    // fails the workspace test build.
    method("ioredis", "connect", true, None),
    method("ioredis", "disconnect", true, None),
    method_sig(
        "mongodb",
        "connect",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method("mongodb", "connect", true, None),
    method("mongodb", "db", true, None),
    method("mongodb", "collection", true, None),
    method("mongodb", "insertOne", true, None),
    method("mongodb", "insertMany", true, None),
    method("mongodb", "find", true, None),
    // #4917 — resolves a parsed document object (BSON-specific types in
    // relaxed extended-JSON shape, e.g. `_id.$oid`), or null.
    method("mongodb", "findOne", true, None),
    method("mongodb", "updateOne", true, None),
    method("mongodb", "updateMany", true, None),
    method("mongodb", "deleteOne", true, None),
    method("mongodb", "deleteMany", true, None),
    method("mongodb", "countDocuments", true, None),
    method("mongodb", "close", true, None),
    method_sig(
        "better-sqlite3",
        "default",
        false,
        None,
        &[p_str("p0")],
        TypeSpec::Any,
    ),
    method("better-sqlite3", "prepare", true, None),
    method("better-sqlite3", "run", true, None),
    method("better-sqlite3", "get", true, None),
    method("better-sqlite3", "all", true, None),
    method("better-sqlite3", "exec", true, None),
    method("better-sqlite3", "close", true, None),
    // Manifest-consistency catch-up (release-sweep gate): NATIVE_MODULE_TABLE
    // had a `raw` row that wasn't mirrored here.
    method("better-sqlite3", "raw", true, None),
    // #1022 — surface the rest of the v8-proxy-materialized methods so
    // the api-docs drift check stays green. `pragma` / `iterate` /
    // `pluck` / `columns` / `transaction` are wired through
    // `perry-jsruntime::bridge::materialize_sqlite_*_proxy` for the V8
    // fallback path (drizzle on better-sqlite3); the native-side
    // codegen lowering already routes the same names through
    // `NATIVE_MODULE_TABLE`.
    method("better-sqlite3", "pragma", true, None),
    method("better-sqlite3", "iterate", true, None),
    method("better-sqlite3", "pluck", true, None),
    method("better-sqlite3", "columns", true, None),
    method("better-sqlite3", "transaction", true, None),
    class("sqlite", "DatabaseSync"),
    class("sqlite", "Session"),
    class("sqlite", "SQLTagStore"),
    class("sqlite", "StatementSync"),
    method("sqlite", "DatabaseSync", false, None),
    method("sqlite", "Session", false, None),
    method("sqlite", "StatementSync", false, None),
    method("sqlite", "backup", false, None),
    property("sqlite", "constants"),
    method("sqlite", "open", true, None),
    method("sqlite", "close", true, None),
    method("sqlite", "__perry_dispose__", true, None),
    method("sqlite", "@@__perry_wk_dispose", true, None),
    method("sqlite", "exec", true, None),
    method("sqlite", "prepare", true, None),
    method("sqlite", "function", true, Some("DatabaseSync")),
    method("sqlite", "aggregate", true, Some("DatabaseSync")),
    method("sqlite", "enableDefensive", true, Some("DatabaseSync")),
    method("sqlite", "setAuthorizer", true, Some("DatabaseSync")),
    method("sqlite", "createTagStore", true, Some("DatabaseSync")),
    method("sqlite", "createSession", true, None),
    method("sqlite", "applyChangeset", true, None),
    method("sqlite", "enableLoadExtension", true, None),
    method("sqlite", "loadExtension", true, None),
    method("sqlite", "location", true, None),
    method("sqlite", "isOpen", true, None),
    method("sqlite", "isTransaction", true, None),
    method("sqlite", "limits", true, None),
    method("sqlite", "changeset", true, None),
    method("sqlite", "patchset", true, None),
    method("sqlite", "run", true, Some("SQLTagStore")),
    method("sqlite", "get", true, Some("SQLTagStore")),
    method("sqlite", "all", true, Some("SQLTagStore")),
    method("sqlite", "iterate", true, Some("SQLTagStore")),
    method("sqlite", "clear", true, Some("SQLTagStore")),
    method("sqlite", "size", true, Some("SQLTagStore")),
    method("sqlite", "capacity", true, Some("SQLTagStore")),
    method("sqlite", "db", true, Some("SQLTagStore")),
    method("sqlite", "run", true, None),
    method("sqlite", "get", true, None),
    method("sqlite", "all", true, None),
    method("sqlite", "iterate", true, None),
    method("sqlite", "columns", true, None),
    method("sqlite", "setReadBigInts", true, None),
    method("sqlite", "setReturnArrays", true, None),
    method("sqlite", "setAllowBareNamedParameters", true, None),
    method("sqlite", "setAllowUnknownNamedParameters", true, None),
    method("sqlite", "sourceSQL", true, None),
    method("sqlite", "expandedSQL", true, None),
    // tursodb (#424). open / exec / execBatch / close /
    // lastInsertRowid / isAutocommit shipped in v0.5.543; queryAll /
    // queryOne shipped in v0.5.553 (close the row-as-object gap by
    // building shapes inside spawn_blocking and resolving with
    // POINTER_TAG'd JsValues).
    method("tursodb", "open", false, None),
    method("tursodb", "exec", true, None),
    method("tursodb", "execBatch", true, None),
    method("tursodb", "queryAll", true, None),
    method("tursodb", "queryOne", true, None),
    method("tursodb", "close", true, None),
    method("tursodb", "lastInsertRowid", true, None),
    method("tursodb", "isAutocommit", true, None),
    // iroh (#425). bind / nodeId / close shipped in v0.5.544; the
    // peer connection + stream surface (connect / acceptOne /
    // openBi / acceptBi / streamWrite / streamFinish /
    // streamReadToEnd / connClose) shipped in v0.5.554. ALPN is
    // hardcoded to `b"perry-iroh/0"` for v0.
    method("iroh", "bind", false, None),
    method("iroh", "nodeId", true, None),
    method("iroh", "close", true, None),
    method("iroh", "connect", true, None),
    method("iroh", "acceptOne", true, None),
    method("iroh", "openBi", true, None),
    method("iroh", "acceptBi", true, None),
    method("iroh", "streamWrite", true, None),
    method("iroh", "streamFinish", true, None),
    method("iroh", "streamReadToEnd", true, None),
    method("iroh", "connClose", true, None),
    property("sea", "default"),
    method("sea", "isSea", false, None),
    method("sea", "getAsset", false, None),
    method("sea", "getAssetAsBlob", false, None),
    method("sea", "getRawAsset", false, None),
    method("sea", "getAssetKeys", false, None),
    property("inspector", "default"),
    method("inspector", "open", false, None).stub_note(
        "accepts port/host but binds no real WebSocket inspector endpoint; sessions are in-process fakes (#4916)",
    ),
    method("inspector", "close", false, None),
    method("inspector", "url", false, None)
        .stub_note("always undefined: Perry never exposes a real inspector endpoint (#4916)"),
    method("inspector", "waitForDebugger", false, None).stub_note(
        "returns immediately after open(); there is no debugger to wait for (#4916)",
    ),
    property("inspector", "console"),
    property("inspector", "Network"),
    class("inspector", "Session"),
    method("inspector", "Session", false, None),
    method("inspector", "connect", true, Some("Session")),
    method("inspector", "connectToMainThread", true, Some("Session")),
    method("inspector", "disconnect", true, Some("Session")),
    method("inspector", "post", true, Some("Session")).stub_note(
        "only Runtime.enable and a canned Runtime.evaluate subset respond; every other protocol method throws Inspector error -32601 (#4916)",
    ),
    method("inspector", "on", true, Some("Session")),
    method("inspector", "once", true, Some("Session")),
    internal_method("inspector.Network", "requestWillBeSent", false, None),
    internal_method("inspector.Network", "responseReceived", false, None),
    internal_method("inspector.Network", "loadingFinished", false, None),
    internal_method("inspector.Network", "loadingFailed", false, None),
    internal_method("inspector.Network", "dataSent", false, None),
    internal_method("inspector.Network", "dataReceived", false, None),
    internal_method("inspector.Network", "webSocketCreated", false, None),
    internal_method("inspector.Network", "webSocketClosed", false, None),
    internal_method(
        "inspector.Network",
        "webSocketHandshakeResponseReceived",
        false,
        None,
    ),
    property("inspector/promises", "default"),
    class("inspector/promises", "Session"),
    method("inspector/promises", "Session", false, None),
    method("inspector/promises", "connect", true, Some("Session")),
    method(
        "inspector/promises",
        "connectToMainThread",
        true,
        Some("Session"),
    ),
    method("inspector/promises", "disconnect", true, Some("Session")),
    method("inspector/promises", "post", true, Some("Session")),
    method("inspector/promises", "on", true, Some("Session")),
    method("inspector/promises", "once", true, Some("Session")),
    method_sig("ws", "Server", false, None, &[p_any("p0")], TypeSpec::Any),
    method_sig(
        "ws",
        "WebSocket",
        false,
        None,
        &[p_str("p0")],
        TypeSpec::Any,
    ),
    method("ws", "on", true, None),
    method("ws", "send", true, None),
    method("ws", "close", true, None),
    // Node-compatible WebSocket ready-state constants. The `ws` package
    // exposes these on both the module/default export and WebSocket class:
    // CONNECTING=0, OPEN=1, CLOSING=2, CLOSED=3.
    property("ws", "CONNECTING"),
    property("ws", "OPEN"),
    property("ws", "CLOSING"),
    property("ws", "CLOSED"),
    // #1113 — `wss.handleUpgrade(req, socket, head, cb)` for a
    // `new WebSocketServer({ noServer: true })`.
    method("ws", "handleUpgrade", true, None),
    // Issue #577 Phase 4 — Client-class methods for the upgrade-path wsId.
    method("ws", "on", true, Some("Client")),
    method("ws", "addListener", true, Some("Client")),
    method("ws", "send", true, Some("Client")),
    method("ws", "close", true, Some("Client")),
    class("ws", "Client"),
    method_sig(
        "ws",
        "sendToClient",
        false,
        None,
        &[p_any("p0"), p_str("p1")],
        TypeSpec::Void,
    ),
    method_sig(
        "ws",
        "closeClient",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Void,
    ),
    // node:dns is currently runtime-only and deterministic: inventory
    // helpers, constants, Resolver method shapes, and lookup/lookupService
    // for localhost/loopback. It does not perform external DNS IO.
    method("dns", "lookup", false, None),
    method("dns", "lookupService", false, None),
    method("dns", "resolve", false, None),
    method("dns", "resolve4", false, None),
    method("dns", "resolve6", false, None),
    method("dns", "resolveAny", false, None),
    method("dns", "resolveCaa", false, None),
    method("dns", "resolveCname", false, None),
    method("dns", "resolveMx", false, None),
    method("dns", "resolveNaptr", false, None),
    method("dns", "resolveNs", false, None),
    method("dns", "resolvePtr", false, None),
    method("dns", "resolveSoa", false, None),
    method("dns", "resolveSrv", false, None),
    method("dns", "resolveTlsa", false, None),
    method("dns", "resolveTxt", false, None),
    method("dns", "reverse", false, None),
    method("dns", "getServers", false, None),
    method("dns", "setServers", false, None),
    method("dns", "setDefaultResultOrder", false, None),
    method("dns", "getDefaultResultOrder", false, None),
    class("dns", "Resolver"),
    method("dns", "Resolver", false, None),
    method("dns", "resolve", true, Some("Resolver")),
    method("dns", "resolve4", true, Some("Resolver")),
    method("dns", "resolve6", true, Some("Resolver")),
    method("dns", "resolveAny", true, Some("Resolver")),
    method("dns", "resolveCaa", true, Some("Resolver")),
    method("dns", "resolveCname", true, Some("Resolver")),
    method("dns", "resolveMx", true, Some("Resolver")),
    method("dns", "resolveNaptr", true, Some("Resolver")),
    method("dns", "resolveNs", true, Some("Resolver")),
    method("dns", "resolvePtr", true, Some("Resolver")),
    method("dns", "resolveSoa", true, Some("Resolver")),
    method("dns", "resolveSrv", true, Some("Resolver")),
    method("dns", "resolveTlsa", true, Some("Resolver")),
    method("dns", "resolveTxt", true, Some("Resolver")),
    method("dns", "reverse", true, Some("Resolver")),
    method("dns", "cancel", true, Some("Resolver")),
    method("dns", "getServers", true, Some("Resolver")),
    method("dns", "setServers", true, Some("Resolver")),
    method("dns", "setLocalAddress", true, Some("Resolver")),
    property("dns", "ADDRCONFIG"),
    property("dns", "V4MAPPED"),
    property("dns", "ALL"),
    property("dns", "NODATA"),
    property("dns", "FORMERR"),
    property("dns", "SERVFAIL"),
    property("dns", "NOTFOUND"),
    property("dns", "NOTIMP"),
    property("dns", "REFUSED"),
    property("dns", "BADQUERY"),
    property("dns", "BADNAME"),
    property("dns", "BADFAMILY"),
    property("dns", "BADRESP"),
    property("dns", "CONNREFUSED"),
    property("dns", "TIMEOUT"),
    property("dns", "EOF"),
    property("dns", "FILE"),
    property("dns", "NOMEM"),
    property("dns", "DESTRUCTION"),
    property("dns", "BADSTR"),
    property("dns", "BADFLAGS"),
    property("dns", "NONAME"),
    property("dns", "BADHINTS"),
    property("dns", "NOTINITIALIZED"),
    property("dns", "LOADIPHLPAPI"),
    property("dns", "ADDRGETNETWORKPARAMS"),
    property("dns", "CANCELLED"),
    method("dns/promises", "lookup", false, None),
    method("dns/promises", "lookupService", false, None),
    method("dns/promises", "resolve", false, None),
    method("dns/promises", "resolve4", false, None),
    method("dns/promises", "resolve6", false, None),
    method("dns/promises", "resolveAny", false, None),
    method("dns/promises", "resolveCaa", false, None),
    method("dns/promises", "resolveCname", false, None),
    method("dns/promises", "resolveMx", false, None),
    method("dns/promises", "resolveNaptr", false, None),
    method("dns/promises", "resolveNs", false, None),
    method("dns/promises", "resolvePtr", false, None),
    method("dns/promises", "resolveSoa", false, None),
    method("dns/promises", "resolveSrv", false, None),
    method("dns/promises", "resolveTlsa", false, None),
    method("dns/promises", "resolveTxt", false, None),
    method("dns/promises", "reverse", false, None),
    method("dns/promises", "getServers", false, None),
    method("dns/promises", "setServers", false, None),
    method("dns/promises", "setDefaultResultOrder", false, None),
    method("dns/promises", "getDefaultResultOrder", false, None),
    class("dns/promises", "Resolver"),
    method("dns/promises", "Resolver", false, None),
    method("dns/promises", "resolve", true, Some("Resolver")),
    method("dns/promises", "resolve4", true, Some("Resolver")),
    method("dns/promises", "resolve6", true, Some("Resolver")),
    method("dns/promises", "resolveAny", true, Some("Resolver")),
    method("dns/promises", "resolveCaa", true, Some("Resolver")),
    method("dns/promises", "resolveCname", true, Some("Resolver")),
    method("dns/promises", "resolveMx", true, Some("Resolver")),
    method("dns/promises", "resolveNaptr", true, Some("Resolver")),
    method("dns/promises", "resolveNs", true, Some("Resolver")),
    method("dns/promises", "resolvePtr", true, Some("Resolver")),
    method("dns/promises", "resolveSoa", true, Some("Resolver")),
    method("dns/promises", "resolveSrv", true, Some("Resolver")),
    method("dns/promises", "resolveTlsa", true, Some("Resolver")),
    method("dns/promises", "resolveTxt", true, Some("Resolver")),
    method("dns/promises", "reverse", true, Some("Resolver")),
    method("dns/promises", "cancel", true, Some("Resolver")),
    method("dns/promises", "getServers", true, Some("Resolver")),
    method("dns/promises", "setServers", true, Some("Resolver")),
    method("dns/promises", "setLocalAddress", true, Some("Resolver")),
    // node:dgram has deterministic in-process loopback coverage for the
    // unicast subset; multicast/queue option methods remain shape-compatible.
    // #3693: default import (`import dgram from "node:dgram"`) === the module
    // namespace (CJS `module.exports`).
    property("dgram", "default"),
    method("dgram", "createSocket", false, None),
    class("dgram", "Socket"),
    method("dgram", "Socket", false, None),
    method("dgram", "send", true, Some("Socket")),
    method("dgram", "bind", true, Some("Socket")),
    method("dgram", "close", true, Some("Socket")),
    method("dgram", "address", true, Some("Socket")),
    method("dgram", "remoteAddress", true, Some("Socket")),
    method("dgram", "connect", true, Some("Socket")),
    method("dgram", "disconnect", true, Some("Socket")),
    method("dgram", "on", true, Some("Socket")),
    method("dgram", "addListener", true, Some("Socket")),
    method("dgram", "once", true, Some("Socket")),
    method("dgram", "off", true, Some("Socket")),
    method("dgram", "removeListener", true, Some("Socket")),
    method("dgram", "emit", true, Some("Socket")),
    method("dgram", "listenerCount", true, Some("Socket")),
    method("dgram", "eventNames", true, Some("Socket")),
    method("dgram", "addMembership", true, Some("Socket")),
    method("dgram", "dropMembership", true, Some("Socket")),
    method("dgram", "addSourceSpecificMembership", true, Some("Socket")),
    method(
        "dgram",
        "dropSourceSpecificMembership",
        true,
        Some("Socket"),
    ),
    method("dgram", "setBroadcast", true, Some("Socket")),
    method("dgram", "setMulticastTTL", true, Some("Socket")),
    method("dgram", "setMulticastLoopback", true, Some("Socket")),
    method("dgram", "setMulticastInterface", true, Some("Socket")),
    method("dgram", "setTTL", true, Some("Socket")),
    method("dgram", "setRecvBufferSize", true, Some("Socket")),
    method("dgram", "setSendBufferSize", true, Some("Socket")),
    method("dgram", "getRecvBufferSize", true, Some("Socket")),
    method("dgram", "getSendBufferSize", true, Some("Socket")),
    method("dgram", "getSendQueueSize", true, Some("Socket")),
    method("dgram", "getSendQueueCount", true, Some("Socket")),
    method("dgram", "ref", true, Some("Socket")),
    method("dgram", "unref", true, Some("Socket")),
    method_sig(
        "net",
        "createConnection",
        false,
        None,
        // p0 = port (number) or options object; p1 = host (string) or
        // connectListener; p2 = connectListener in positional form.
        // Issue #770 widened to accept the options-object overload.
        &[p_any("p0"), p_any("p1"), p_any("p2")],
        TypeSpec::Any,
    ),
    method_sig(
        "net",
        "connect",
        false,
        None,
        &[p_any("p0"), p_any("p1"), p_any("p2")],
        TypeSpec::Any,
    ),
    method_sig(
        "net",
        "createServer",
        false,
        None,
        &[p_any("p0"), p_any("p1")],
        TypeSpec::Any,
    ),
    method_sig(
        "net",
        "Server",
        false,
        None,
        &[p_any("p0"), p_any("p1")],
        TypeSpec::Any,
    ),
    method_sig("net", "Socket", false, None, &[], TypeSpec::Any),
    method_sig("net", "Stream", false, None, &[], TypeSpec::Any),
    method_sig("net", "BlockList", false, None, &[], TypeSpec::Any),
    method_sig(
        "net",
        "SocketAddress",
        false,
        None,
        &[p_any("options")],
        TypeSpec::Any,
    ),
    method("net", "isBlockList", false, Some("BlockList")),
    method("net", "parse", false, Some("SocketAddress")),
    method_sig(
        "net",
        "_normalizeArgs",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method_sig(
        "net",
        "_createServerHandle",
        false,
        None,
        &[
            p_any("p0"),
            p_any("p1"),
            p_any("p2"),
            p_any("p3"),
            p_any("p4"),
        ],
        TypeSpec::Any,
    ),
    method("net", "connect", true, Some("Socket")),
    method("net", "write", true, Some("Socket")),
    method("net", "end", true, Some("Socket")),
    method("net", "destroy", true, Some("Socket")),
    method("net", "on", true, Some("Socket")),
    method("net", "upgradeToTLS", true, Some("Socket")),
    method("timers", "setTimeout", false, None),
    method("timers", "clearTimeout", false, None),
    method("timers", "setImmediate", false, None),
    method("timers", "clearImmediate", false, None),
    method("timers", "setInterval", false, None),
    method("timers", "clearInterval", false, None),
    property("timers", "promises"),
    method("timers/promises", "setTimeout", false, None),
    method("timers/promises", "setImmediate", false, None),
    method("timers/promises", "setInterval", false, None),
    property("timers/promises", "scheduler"),
    // Issue #1852 — chainable no-op `net.Socket` option setters. Perry's
    // TCP transport doesn't model Nagle/keep-alive/idle-timeout or read
    // back-pressure yet, but the methods must be callable (and return the
    // socket for chaining) instead of throwing "not a function". These
    // names also cover the `net.Server` `ref`/`unref`/`setTimeout` rows
    // below (`module_has_symbol` is name-based), so they unblock the
    // strict-API gate for both classes.
    method("net", "setNoDelay", true, Some("Socket")),
    method("net", "setKeepAlive", true, Some("Socket")),
    method("net", "getTypeOfService", true, Some("Socket")),
    method("net", "setTypeOfService", true, Some("Socket")),
    method("net", "setTimeout", true, Some("Socket")),
    method("net", "setEncoding", true, Some("Socket")),
    method("net", "setDefaultEncoding", true, Some("Socket")),
    method("net", "pause", true, Some("Socket")),
    method("net", "resume", true, Some("Socket")),
    method("net", "ref", true, Some("Socket")),
    method("net", "unref", true, Some("Socket")),
    method("net", "cork", true, Some("Socket")),
    method("net", "uncork", true, Some("Socket")),
    // Issue #2131 — lifecycle + EventEmitter surface beyond `.on`.
    // `address()` resolves to a real `{ port, family, address }` object;
    // the rest match the Node EventEmitter shape so any-typed
    // receivers (the accepted-socket arg of
    // `server.on('connection', s => …)` is the dominant case) keep
    // dispatching instead of throwing "not a function".
    method("net", "address", true, Some("Socket")),
    // #2549 — `net.Socket` state / counter / metadata property getters.
    // Lowered as zero-arg `NativeMethodCall`s (bare member reads), so the
    // manifest counterpart is a `has_receiver: true` Method entry.
    method("net", "pending", true, Some("Socket")),
    method("net", "connecting", true, Some("Socket")),
    method("net", "destroyed", true, Some("Socket")),
    method("net", "readyState", true, Some("Socket")),
    method("net", "bytesRead", true, Some("Socket")),
    method("net", "bytesWritten", true, Some("Socket")),
    method("net", "timeout", true, Some("Socket")),
    method("net", "localAddress", true, Some("Socket")),
    method("net", "localPort", true, Some("Socket")),
    method("net", "localFamily", true, Some("Socket")),
    method("net", "remoteAddress", true, Some("Socket")),
    method("net", "remotePort", true, Some("Socket")),
    method("net", "remoteFamily", true, Some("Socket")),
    method("net", "bufferSize", true, Some("Socket")),
    method(
        "net",
        "autoSelectFamilyAttemptedAddresses",
        true,
        Some("Socket"),
    ),
    method("net", "once", true, Some("Socket")),
    method("net", "addListener", true, Some("Socket")),
    method("net", "off", true, Some("Socket")),
    method("net", "removeListener", true, Some("Socket")),
    method("net", "removeAllListeners", true, Some("Socket")),
    method("net", "listenerCount", true, Some("Socket")),
    method("net", "eventNames", true, Some("Socket")),
    // Issue #2211 — `socket.listeners(event)` / `socket.rawListeners(event)`.
    // Returns a real JS array of registered callbacks; the introspection
    // methods `test-http-agent-*` exercises after `request.on('socket', ...)`.
    method("net", "listeners", true, Some("Socket")),
    method("net", "rawListeners", true, Some("Socket")),
    method("net", "resetAndDestroy", true, Some("Socket")),
    method("net", "addAddress", true, Some("BlockList")),
    method("net", "addRange", true, Some("BlockList")),
    method("net", "addSubnet", true, Some("BlockList")),
    method("net", "check", true, Some("BlockList")),
    method("net", "toJSON", true, Some("BlockList")),
    method("net", "fromJSON", true, Some("BlockList")),
    method("net", "rules", true, Some("BlockList")),
    method("net", "address", true, Some("SocketAddress")),
    method("net", "family", true, Some("SocketAddress")),
    method("net", "port", true, Some("SocketAddress")),
    method("net", "flowlabel", true, Some("SocketAddress")),
    method("net", "getProtocol", true, Some("Socket")),
    method("net", "getCipher", true, Some("Socket")),
    method("net", "getPeerCertificate", true, Some("Socket")),
    method("net", "getCertificate", true, Some("Socket")),
    method("net", "getSession", true, Some("Socket")),
    method("net", "isSessionReused", true, Some("Socket")),
    method("net", "exportKeyingMaterial", true, Some("Socket")),
    method("net", "setMaxSendFragment", true, Some("Socket")),
    // Issue #1123 followup — `net.Server` instance methods backing
    // `createServer(...).listen/.close/.address/.on`. Mirrors the
    // shape of the http-server rows at entries.rs:2298. The
    // factory `createServer(...)` itself doesn't show up in the
    // dispatch table because it lowers to `Expr::NetCreateServer`
    // (handled in `crates/perry-codegen/src/expr.rs`), not a
    // NativeMethodCall — same reason `("http", "createServer")`
    // appears here but not as a dispatch-table row.
    method("net", "listen", true, Some("Server")),
    method("net", "listening", true, Some("Server")),
    method("net", "maxConnections", true, Some("Server")),
    method("net", "dropMaxConnection", true, Some("Server")),
    method("net", "__set_maxConnections", true, Some("Server")),
    method("net", "__set_dropMaxConnection", true, Some("Server")),
    method("net", "close", true, Some("Server")),
    method("net", "address", true, Some("Server")),
    method("net", "addListener", true, Some("Server")),
    // Issue #2131 — `net.Server` EventEmitter surface (twin of the
    // Socket entries above). Same handle namespace, same listener +
    // once-flag storage.
    method("net", "once", true, Some("Server")),
    method("net", "off", true, Some("Server")),
    method("net", "removeListener", true, Some("Server")),
    method("net", "removeAllListeners", true, Some("Server")),
    method("net", "listenerCount", true, Some("Server")),
    method("net", "eventNames", true, Some("Server")),
    method("net", "getConnections", true, Some("Server")),
    // Issue #2211 — `server.listeners(event)` / `server.rawListeners(event)`,
    // twin of the Socket entries above (shared handle/listener namespace).
    method("net", "listeners", true, Some("Server")),
    method("net", "rawListeners", true, Some("Server")),
    // Issue #811 — IP classification helpers + Happy-Eyeballs default
    // accessors. Pure string/global-flag functions.
    method("net", "isIP", false, None),
    method("net", "isIPv4", false, None),
    method("net", "isIPv6", false, None),
    method("net", "getDefaultAutoSelectFamily", false, None),
    method("net", "setDefaultAutoSelectFamily", false, None),
    method(
        "net",
        "getDefaultAutoSelectFamilyAttemptTimeout",
        false,
        None,
    ),
    method(
        "net",
        "setDefaultAutoSelectFamilyAttemptTimeout",
        false,
        None,
    ),
    method_sig(
        "tls",
        "checkServerIdentity",
        false,
        None,
        &[p_any("hostname"), p_any("cert")],
        TypeSpec::Any,
    ),
    method_sig(
        "tls",
        "createSecureContext",
        false,
        None,
        &[p_any("options")],
        TypeSpec::Any,
    ),
    method_sig(
        "tls",
        "getCACertificates",
        false,
        None,
        &[p_any("type")],
        TypeSpec::Any,
    ),
    method("tls", "getCiphers", false, None),
    method_sig(
        "tls",
        "setDefaultCACertificates",
        false,
        None,
        &[p_any("certs")],
        TypeSpec::Any,
    ),
    method_sig(
        "tls",
        "SecureContext",
        false,
        None,
        &[p_any("options")],
        TypeSpec::Any,
    ),
    property("tls", "DEFAULT_ECDH_CURVE"),
    property("tls", "DEFAULT_MAX_VERSION"),
    property("tls", "DEFAULT_MIN_VERSION"),
    property("tls", "DEFAULT_CIPHERS"),
    property("tls", "rootCertificates"),
    property("tls", "CLIENT_RENEG_LIMIT"),
    property("tls", "CLIENT_RENEG_WINDOW"),
    // #4971 — all-any params: the runtime resolves Node's overloads
    // (`connect(options[, cb])`, `connect(port[, host][, options][, cb])`)
    // plus the legacy positional `(host, port, servername?, verify?)` from
    // the raw NaN-boxed args; the old `(string, any, string, any)` shape
    // string-coerced an options-object first arg.
    method_sig(
        "tls",
        "connect",
        false,
        None,
        &[p_any("p0"), p_any("p1"), p_any("p2"), p_any("p3")],
        TypeSpec::Any,
    ),
    class("tls", "SecureContext"),
    method_sig(
        "tls",
        "createServer",
        false,
        None,
        &[p_any("options"), p_any("secureConnectionListener")],
        TypeSpec::Any,
    ),
    method_sig(
        "tls",
        "Server",
        false,
        None,
        &[p_any("options"), p_any("secureConnectionListener")],
        TypeSpec::Any,
    ),
    method_sig(
        "tls",
        "TLSSocket",
        false,
        None,
        &[p_any("socket"), p_any("options")],
        TypeSpec::Any,
    ),
    method("tls", "listen", true, Some("Server")),
    method("tls", "close", true, Some("Server")),
    method("tls", "address", true, Some("Server")),
    method("tls", "on", true, Some("Server")),
    method("tls", "addListener", true, Some("Server")),
    method("tls", "once", true, Some("Server")),
    method("tls", "off", true, Some("Server")),
    method("tls", "removeListener", true, Some("Server")),
    method("tls", "removeAllListeners", true, Some("Server")),
    method("tls", "listenerCount", true, Some("Server")),
    method("tls", "eventNames", true, Some("Server")),
    method("tls", "setSecureContext", true, Some("Server")),
    method("tls", "getTicketKeys", true, Some("Server")),
    method("tls", "setTicketKeys", true, Some("Server")),
    property("events", "default"),
    method_sig("events", "EventEmitter", false, None, &[], TypeSpec::Any),
    method_sig(
        "events",
        "EventEmitterAsyncResource",
        false,
        None,
        &[p_any("options")],
        TypeSpec::Any,
    ),
    method("events", "on", true, None),
    method("events", "emit", true, None),
    method("events", "removeListener", true, None),
    method("events", "removeAllListeners", true, None),
    // EventEmitter additions wired in v0.5.922 (issue #850).
    property("events", "defaultMaxListeners"),
    property("events", "usingDomains"),
    property("events", "errorMonitor"),
    property("events", "captureRejections"),
    property("events", "captureRejectionSymbol"),
    method("events", "once", true, None),
    method("events", "addListener", true, None),
    method("events", "prependListener", true, None),
    method("events", "prependOnceListener", true, None),
    method("events", "off", true, None),
    method("events", "listenerCount", true, None),
    method("events", "listeners", true, None),
    method("events", "rawListeners", true, None),
    method("events", "eventNames", true, None),
    method("events", "setMaxListeners", true, None),
    method("events", "getMaxListeners", true, None),
    method("events", "domain", true, None),
    method("events", "asyncId", true, Some("EventEmitterAsyncResource")),
    method(
        "events",
        "triggerAsyncId",
        true,
        Some("EventEmitterAsyncResource"),
    ),
    method(
        "events",
        "asyncResource",
        true,
        Some("EventEmitterAsyncResource"),
    ),
    method(
        "events",
        "emitDestroy",
        true,
        Some("EventEmitterAsyncResource"),
    ),
    // Module-level helpers (`events.once` / `events.getEventListeners` /
    // `events.listenerCount` / `events.getMaxListeners` /
    // `events.setMaxListeners`).
    method("events", "once", false, None),
    method("events", "addAbortListener", false, None),
    method("events", "getEventListeners", false, None),
    method("events", "listenerCount", false, None),
    method("events", "getMaxListeners", false, None),
    method("events", "setMaxListeners", false, None),
    method("events", "init", false, None),
    // Module-level `events.on(emitter, name)` — async-iterable queue,
    // PR #1257.
    method("events", "on", false, None),
    method_sig("domain", "Domain", false, None, &[], TypeSpec::Any),
    method_sig("domain", "createDomain", false, None, &[], TypeSpec::Any),
    method_sig("domain", "create", false, None, &[], TypeSpec::Any),
    property("domain", "_stack"),
    property("domain", "active"),
    property("domain", "members"),
    method("domain", "on", true, None),
    method("domain", "addListener", true, None),
    method("domain", "emit", true, None),
    method("domain", "run", true, None),
    method("domain", "bind", true, None),
    method("domain", "intercept", true, None),
    method("domain", "add", true, None),
    method("domain", "remove", true, None),
    method("domain", "enter", true, None),
    method("domain", "exit", true, None),
    method_sig(
        "lru-cache",
        "default",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method("lru-cache", "get", true, None),
    method("lru-cache", "set", true, None),
    method("lru-cache", "has", true, None),
    method("lru-cache", "delete", true, None),
    method("lru-cache", "clear", true, None),
    method("lru-cache", "size", true, None),
    method("commander", "name", true, None),
    method("commander", "description", true, None),
    method("commander", "version", true, None),
    method("commander", "command", true, None),
    method("commander", "option", true, None),
    method("commander", "requiredOption", true, None),
    method("commander", "action", true, None),
    method("commander", "parse", true, None),
    method("commander", "opts", true, None),
    method("commander", "argument", true, None),
    // `program.args` is a bare member read modeled as a property for the
    // `.d.ts` surface (`export const args`), but the dispatch table lowers
    // it to a 0-arg instance getter row (`commander::args`, has_receiver).
    // The drift gate (every_dispatch_entry_has_manifest_counterpart) wants
    // a Method counterpart for that row; keep both — the has_receiver
    // method isn't emitted as a module export, so docs are unchanged (#5137).
    method("commander", "args", true, None),
    property("commander", "args"),
    property("async_hooks", "default"),
    property("async_hooks", "asyncWrapProviders"),
    method("async_hooks", "createHook", false, None),
    method("async_hooks", "executionAsyncId", false, None),
    method("async_hooks", "executionAsyncResource", false, None),
    method("async_hooks", "triggerAsyncId", false, None),
    method("async_hooks", "bind", false, Some("AsyncLocalStorage")),
    method("async_hooks", "snapshot", false, Some("AsyncLocalStorage")),
    method("async_hooks", "enable", true, Some("AsyncHook")),
    method("async_hooks", "run", true, None),
    method("async_hooks", "getStore", true, None),
    method("async_hooks", "enterWith", true, None),
    method("async_hooks", "exit", true, None),
    method("async_hooks", "disable", true, None),
    method("async_hooks", "asyncId", true, Some("AsyncResource")),
    method("async_hooks", "triggerAsyncId", true, Some("AsyncResource")),
    method("async_hooks", "emitDestroy", true, Some("AsyncResource")),
    method(
        "async_hooks",
        "runInAsyncScope",
        true,
        Some("AsyncResource"),
    ),
    method("async_hooks", "bind", false, Some("AsyncResource")),
    method("async_hooks", "bind", true, Some("AsyncResource")),
    // #2875: DisposableStack / AsyncDisposableStack instance methods. The
    // `__disposable__` module is internal (synthesized by the var-decl
    // native-instance registration), so it has no JS import surface — these
    // entries exist solely to satisfy the dispatch-table drift gate.
    method("__disposable__", "use", true, None),
    method("__disposable__", "adopt", true, None),
    method("__disposable__", "defer", true, None),
    method("__disposable__", "dispose", true, None),
    method("__disposable__", "disposeAsync", true, None),
    method("__disposable__", "move", true, None),
    method("__disposable__", "disposed", true, None),
    // AsyncResource — Nest's `@nestjs/core` request-scoped DI uses
    // this to bind a callback to a synthetic async resource. The
    // stub in `node:async_hooks` JS module satisfies callers that
    // only need the `runInAsyncScope` shape.
    class("async_hooks", "AsyncResource"),
    class("async_hooks", "AsyncLocalStorage"),
    method("decimal.js", "plus", true, None),
    method("decimal.js", "minus", true, None),
    method("decimal.js", "times", true, None),
    method("decimal.js", "div", true, None),
    method("decimal.js", "mod", true, None),
    method("decimal.js", "pow", true, None),
    method("decimal.js", "sqrt", true, None),
    method("decimal.js", "abs", true, None),
    method("decimal.js", "neg", true, None),
    method("decimal.js", "round", true, None),
    method("decimal.js", "floor", true, None),
    method("decimal.js", "ceil", true, None),
    method("decimal.js", "toFixed", true, None),
    method("decimal.js", "toString", true, None),
    method("decimal.js", "toNumber", true, None),
    method("decimal.js", "valueOf", true, None),
    method("decimal.js", "eq", true, None),
    method("decimal.js", "lt", true, None),
    method("decimal.js", "lte", true, None),
    method("decimal.js", "gt", true, None),
    method("decimal.js", "gte", true, None),
    method("decimal.js", "cmp", true, None),
    method("decimal.js", "isZero", true, None),
    method("decimal.js", "isPositive", true, None),
    method("decimal.js", "isNegative", true, None),
    method_sig("uuid", "v4", false, None, &[], TypeSpec::String),
    method_sig("uuid", "v1", false, None, &[], TypeSpec::String),
    method_sig("uuid", "v7", false, None, &[], TypeSpec::String),
    method_sig(
        "uuid",
        "v5",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "name",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "namespace",
                ty: TypeSpec::String,
                optional: false,
            },
        ],
        TypeSpec::String,
    ),
    method_sig(
        "uuid",
        "v3",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "name",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "namespace",
                ty: TypeSpec::String,
                optional: false,
            },
        ],
        TypeSpec::String,
    ),
    method_sig(
        "uuid",
        "validate",
        false,
        None,
        &[ParamSpec::Named {
            name: "id",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Bool,
    ),
    method_sig(
        "uuid",
        "version",
        false,
        None,
        &[ParamSpec::Named {
            name: "id",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Number,
    ),
    method_sig(
        "jsonwebtoken",
        "sign",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "payload",
                ty: TypeSpec::Any,
                optional: false,
            },
            ParamSpec::Named {
                name: "secret",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "options",
                ty: TypeSpec::Any,
                optional: true,
            },
            // #915: FFI's 4th arg is `kid_ptr: *const StringHeader` — the
            // dispatch table padding zeroes it when the user doesn't pass
            // it. Surfacing the slot in the manifest keeps the
            // #512 arity-drift assertion happy without forcing every
            // caller to write a 4th positional arg.
            ParamSpec::Named {
                name: "kid",
                ty: TypeSpec::String,
                optional: true,
            },
        ],
        TypeSpec::String,
    ),
    method_sig(
        "jsonwebtoken",
        "verify",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "token",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "secret",
                ty: TypeSpec::String,
                optional: false,
            },
        ],
        TypeSpec::Any,
    ),
    method_sig(
        "jsonwebtoken",
        "decode",
        false,
        None,
        &[ParamSpec::Named {
            name: "token",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Any,
    ),
    method_sig(
        "nodemailer",
        "createTransport",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
    method("nodemailer", "sendMail", true, None),
    method("nodemailer", "verify", true, None),
    method_sig("dotenv", "config", false, None, &[], TypeSpec::Any),
    method_sig(
        "nanoid",
        "nanoid",
        false,
        None,
        &[ParamSpec::Named {
            name: "size",
            ty: TypeSpec::Number,
            optional: false,
        }],
        TypeSpec::String,
    ),
    method_sig(
        "slugify",
        "default",
        false,
        None,
        &[p_str("p0"), p_str("p1"), p_str("p2")],
        TypeSpec::String,
    ),
    method_sig(
        "slugify",
        "slugify",
        false,
        None,
        &[p_str("p0"), p_str("p1"), p_str("p2")],
        TypeSpec::String,
    ),
    method_sig(
        "validator",
        "isEmail",
        false,
        None,
        &[ParamSpec::Named {
            name: "s",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Bool,
    ),
    method_sig(
        "validator",
        "isURL",
        false,
        None,
        &[ParamSpec::Named {
            name: "s",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Bool,
    ),
    method_sig(
        "validator",
        "isUUID",
        false,
        None,
        &[ParamSpec::Named {
            name: "s",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Bool,
    ),
    method_sig(
        "validator",
        "isJSON",
        false,
        None,
        &[ParamSpec::Named {
            name: "s",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Bool,
    ),
    method_sig(
        "validator",
        "isEmpty",
        false,
        None,
        &[ParamSpec::Named {
            name: "s",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Bool,
    ),
    // #4917 — real retry semantics: options (numOfAttempts/startingDelay/
    // timeMultiple/maxDelay/delayFirstAttempt/jitter/retry) honored;
    // Promise-returning tasks retry on rejection via promise reactions.
    method_sig(
        "exponential-backoff",
        "backOff",
        false,
        None,
        &[p_any("p0"), p_any("p1")],
        TypeSpec::Any,
    ),
    method_sig(
        "argon2",
        "hash",
        false,
        None,
        &[ParamSpec::Named {
            name: "password",
            ty: TypeSpec::String,
            optional: false,
        }],
        TypeSpec::Any,
    ),
    method_sig(
        "argon2",
        "verify",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "hash",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "password",
                ty: TypeSpec::String,
                optional: false,
            },
        ],
        TypeSpec::Any,
    ),
    method_sig(
        "bcrypt",
        "hash",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "password",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "saltOrRounds",
                ty: TypeSpec::Any,
                optional: false,
            },
        ],
        TypeSpec::Any,
    ),
    method_sig(
        "bcrypt",
        "compare",
        false,
        None,
        &[
            ParamSpec::Named {
                name: "plaintext",
                ty: TypeSpec::String,
                optional: false,
            },
            ParamSpec::Named {
                name: "hash",
                ty: TypeSpec::String,
                optional: false,
            },
        ],
        TypeSpec::Any,
    ),
    // #5731 — `perry` embedded-asset API for standalone executables.
    // `readEmbedded(path)` returns the bytes of an asset baked in via
    // `perry compile --embed`; `embeddedFiles` / `isStandaloneExecutable`
    // are value (property) exports resolved at read time.
    method_sig(
        "perry",
        "readEmbedded",
        false,
        None,
        &[p_str("path")],
        TypeSpec::Buffer,
    ),
    method_sig("perry", "embeddedFiles", false, None, &[], TypeSpec::Any),
    property("perry", "isStandaloneExecutable"),
    method_sig(
        "perry/thread",
        "parallelMap",
        false,
        None,
        &[p_any("p0"), p_any("p1")],
        TypeSpec::Any,
    ),
    method_sig(
        "perry/thread",
        "parallelFilter",
        false,
        None,
        &[p_any("p0"), p_any("p1")],
        TypeSpec::Any,
    ),
    // `spawn(fn)` runs `fn` on a background OS thread and hands back a
    // Promise that resolves to the closure's return value (#4022). The
    // resolved value's type isn't statically known, so `Promise<any>`.
    method_sig(
        "perry/thread",
        "spawn",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Promise,
    ),
    method_sig(
        "lodash",
        "chunk",
        false,
        None,
        &[p_any("p0"), p_any("p1")],
        TypeSpec::Any,
    ),
    method_sig(
        "lodash",
        "compact",
        false,
        None,
        &[p_any("p0")],
        TypeSpec::Any,
    ),
];
