use super::super::*;
use super::*;

pub(crate) const NODE_CORE_MODULE_SEA_TLS_TEST_ROWS: &[NativeModSig] = &[
    // ========== Node module ==========
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "createRequire",
        class_filter: None,
        // #6644: the devirt wrapper arms the nm/submod install-all hooks (the
        // returned require closure resolves builtins from a runtime string, so
        // codegen can't emit precise per-module installs). Mirrors
        // js_process_get_builtin_module_devirt.
        runtime: "js_module_create_require_devirt",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "Module",
        class_filter: None,
        runtime: "js_module_module_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "enableCompileCache",
        class_filter: None,
        runtime: "js_module_enable_compile_cache",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "flushCompileCache",
        class_filter: None,
        runtime: "js_module_flush_compile_cache",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "getCompileCacheDir",
        class_filter: None,
        runtime: "js_module_get_compile_cache_dir",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "getSourceMapsSupport",
        class_filter: None,
        runtime: "js_module_get_source_maps_support",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_findPath",
        class_filter: None,
        runtime: "js_module_find_path",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_initPaths",
        class_filter: None,
        runtime: "js_module_init_paths",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_load",
        class_filter: None,
        runtime: "js_module_load",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_nodeModulePaths",
        class_filter: None,
        runtime: "js_module_node_module_paths",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_preloadModules",
        class_filter: None,
        runtime: "js_module_preload_modules",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_resolveFilename",
        class_filter: None,
        runtime: "js_module_resolve_filename",
        args: &[NA_F64, NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "_resolveLookupPaths",
        class_filter: None,
        runtime: "js_module_resolve_lookup_paths",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "isBuiltin",
        class_filter: None,
        runtime: "js_module_is_builtin",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "register",
        class_filter: None,
        runtime: "js_module_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "registerHooks",
        class_filter: None,
        runtime: "js_module_register_hooks",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "SourceMap",
        class_filter: None,
        runtime: "js_module_source_map_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "setSourceMapsSupport",
        class_filter: None,
        runtime: "js_module_set_source_maps_support",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "stripTypeScriptTypes",
        class_filter: None,
        runtime: "js_module_strip_typescript_types",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #3120: module.findPackageJSON(specifier[, base]) — walks parent
    // directories from the resolved specifier looking for package.json.
    // `specifier` (string) and `base` (string or URL object) both ride in
    // the NaN-boxed F64 slot; a missing `base` is padded with TAG_UNDEFINED.
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "findPackageJSON",
        class_filter: None,
        runtime: "js_module_find_package_json",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node sea ==========
    NativeModSig {
        module: "sea",
        has_receiver: false,
        method: "isSea",
        class_filter: None,
        runtime: "js_sea_is_sea",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sea",
        has_receiver: false,
        method: "getAsset",
        class_filter: None,
        runtime: "js_sea_get_asset",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sea",
        has_receiver: false,
        method: "getAssetAsBlob",
        class_filter: None,
        runtime: "js_sea_get_asset_as_blob",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sea",
        has_receiver: false,
        method: "getRawAsset",
        class_filter: None,
        runtime: "js_sea_get_raw_asset",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sea",
        has_receiver: false,
        method: "getAssetKeys",
        class_filter: None,
        runtime: "js_sea_get_asset_keys",
        args: &[],
        ret: NR_F64,
    },
    // ========== Node TLS helper surface ==========
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "getCiphers",
        class_filter: None,
        runtime: "js_tls_get_ciphers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "getCACertificates",
        class_filter: None,
        runtime: "js_tls_get_ca_certificates",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "setDefaultCACertificates",
        class_filter: None,
        runtime: "js_tls_set_default_ca_certificates",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "checkServerIdentity",
        class_filter: None,
        runtime: "js_tls_check_server_identity",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "createSecureContext",
        class_filter: None,
        runtime: "js_tls_create_secure_context",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "SecureContext",
        class_filter: None,
        runtime: "js_tls_secure_context_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node test runner ==========
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "test",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "skip",
        class_filter: None,
        runtime: "js_node_test_skip",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "todo",
        class_filter: None,
        runtime: "js_node_test_todo",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "only",
        class_filter: None,
        runtime: "js_node_test_only",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "suite",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "describe",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "it",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "before",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "after",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "beforeEach",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "afterEach",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "run",
        class_filter: None,
        runtime: "js_node_test_run",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "fn",
        class_filter: None,
        runtime: "js_node_test_mock_fn",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "method",
        class_filter: None,
        runtime: "js_node_test_mock_method",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "getter",
        class_filter: None,
        runtime: "js_node_test_mock_getter",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setter",
        class_filter: None,
        runtime: "js_node_test_mock_setter",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "property",
        class_filter: None,
        runtime: "js_node_test_mock_property",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "reset",
        class_filter: None,
        runtime: "js_node_test_mock_reset",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "restoreAll",
        class_filter: None,
        runtime: "js_node_test_mock_restore_all",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setDefaultSnapshotSerializers",
        class_filter: None,
        runtime: "js_node_test_snapshot_set_default_serializers",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setResolveSnapshotPath",
        class_filter: None,
        runtime: "js_node_test_snapshot_set_resolve_snapshot_path",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "enable",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_enable",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "tick",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_tick",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "runAll",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_run_all",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setTime",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_set_time",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "reset",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_reset",
        args: &[],
        ret: NR_F64,
    },
];
