use super::*;

macro_rules! dns_resolver_record_sig {
    ($module:literal, $method:literal, $runtime:literal) => {
        NativeModSig {
            module: $module,
            has_receiver: true,
            method: $method,
            class_filter: Some("Resolver"),
            runtime: $runtime,
            args: &[NA_VARARGS],
            ret: NR_F64,
        }
    };
}

/// node:dns + node:dns/promises shape-stub rows (#793). Split out of
/// node_core.rs to keep that file under the 2000-line CI gate.
pub(super) const NODE_DNS_ROWS: &[NativeModSig] = &[
    // ========== Node dns shape stubs ==========
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "lookup",
        class_filter: None,
        runtime: "js_dns_lookup",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "lookupService",
        class_filter: None,
        runtime: "js_dns_lookup_service",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_dns_resolve",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolve4",
        class_filter: None,
        runtime: "js_dns_resolve4",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolve6",
        class_filter: None,
        runtime: "js_dns_resolve6",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveAny",
        class_filter: None,
        runtime: "js_dns_resolve_any",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveCaa",
        class_filter: None,
        runtime: "js_dns_resolve_caa",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveCname",
        class_filter: None,
        runtime: "js_dns_resolve_cname",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveMx",
        class_filter: None,
        runtime: "js_dns_resolve_mx",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveNaptr",
        class_filter: None,
        runtime: "js_dns_resolve_naptr",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveNs",
        class_filter: None,
        runtime: "js_dns_resolve_ns",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolvePtr",
        class_filter: None,
        runtime: "js_dns_resolve_ptr",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveSoa",
        class_filter: None,
        runtime: "js_dns_resolve_soa",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveSrv",
        class_filter: None,
        runtime: "js_dns_resolve_srv",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveTlsa",
        class_filter: None,
        runtime: "js_dns_resolve_tlsa",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveTxt",
        class_filter: None,
        runtime: "js_dns_resolve_txt",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "reverse",
        class_filter: None,
        runtime: "js_dns_reverse",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "getServers",
        class_filter: None,
        runtime: "js_dns_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "setServers",
        class_filter: None,
        runtime: "js_dns_set_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "setDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_set_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "getDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_get_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "Resolver",
        class_filter: None,
        runtime: "js_dns_resolver_new",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    dns_resolver_record_sig!("dns", "resolve", "js_dns_resolver_resolve"),
    dns_resolver_record_sig!("dns", "resolve4", "js_dns_resolver_resolve4"),
    dns_resolver_record_sig!("dns", "resolve6", "js_dns_resolver_resolve6"),
    dns_resolver_record_sig!("dns", "resolveAny", "js_dns_resolver_resolve_any"),
    dns_resolver_record_sig!("dns", "resolveCaa", "js_dns_resolver_resolve_caa"),
    dns_resolver_record_sig!("dns", "resolveCname", "js_dns_resolver_resolve_cname"),
    dns_resolver_record_sig!("dns", "resolveMx", "js_dns_resolver_resolve_mx"),
    dns_resolver_record_sig!("dns", "resolveNaptr", "js_dns_resolver_resolve_naptr"),
    dns_resolver_record_sig!("dns", "resolveNs", "js_dns_resolver_resolve_ns"),
    dns_resolver_record_sig!("dns", "resolvePtr", "js_dns_resolver_resolve_ptr"),
    dns_resolver_record_sig!("dns", "resolveSoa", "js_dns_resolver_resolve_soa"),
    dns_resolver_record_sig!("dns", "resolveSrv", "js_dns_resolver_resolve_srv"),
    dns_resolver_record_sig!("dns", "resolveTlsa", "js_dns_resolver_resolve_tlsa"),
    dns_resolver_record_sig!("dns", "resolveTxt", "js_dns_resolver_resolve_txt"),
    dns_resolver_record_sig!("dns", "reverse", "js_dns_resolver_reverse"),
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "cancel",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "getServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "setServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_set_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "setLocalAddress",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "lookup",
        class_filter: None,
        runtime: "js_dns_promises_lookup",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "lookupService",
        class_filter: None,
        runtime: "js_dns_promises_lookup_service",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_dns_promises_resolve",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolve4",
        class_filter: None,
        runtime: "js_dns_promises_resolve4",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolve6",
        class_filter: None,
        runtime: "js_dns_promises_resolve6",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveAny",
        class_filter: None,
        runtime: "js_dns_promises_resolve_any",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveCaa",
        class_filter: None,
        runtime: "js_dns_promises_resolve_caa",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveCname",
        class_filter: None,
        runtime: "js_dns_promises_resolve_cname",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveMx",
        class_filter: None,
        runtime: "js_dns_promises_resolve_mx",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveNaptr",
        class_filter: None,
        runtime: "js_dns_promises_resolve_naptr",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveNs",
        class_filter: None,
        runtime: "js_dns_promises_resolve_ns",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolvePtr",
        class_filter: None,
        runtime: "js_dns_promises_resolve_ptr",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveSoa",
        class_filter: None,
        runtime: "js_dns_promises_resolve_soa",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveSrv",
        class_filter: None,
        runtime: "js_dns_promises_resolve_srv",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveTlsa",
        class_filter: None,
        runtime: "js_dns_promises_resolve_tlsa",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveTxt",
        class_filter: None,
        runtime: "js_dns_promises_resolve_txt",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "reverse",
        class_filter: None,
        runtime: "js_dns_promises_reverse",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "getServers",
        class_filter: None,
        runtime: "js_dns_promises_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "setServers",
        class_filter: None,
        runtime: "js_dns_promises_set_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "setDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_set_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "getDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_get_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "Resolver",
        class_filter: None,
        runtime: "js_dns_promises_resolver_new",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    dns_resolver_record_sig!(
        "dns/promises",
        "resolve",
        "js_dns_promises_resolver_resolve"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolve4",
        "js_dns_promises_resolver_resolve4"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolve6",
        "js_dns_promises_resolver_resolve6"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveAny",
        "js_dns_promises_resolver_resolve_any"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveCaa",
        "js_dns_promises_resolver_resolve_caa"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveCname",
        "js_dns_promises_resolver_resolve_cname"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveMx",
        "js_dns_promises_resolver_resolve_mx"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveNaptr",
        "js_dns_promises_resolver_resolve_naptr"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveNs",
        "js_dns_promises_resolver_resolve_ns"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolvePtr",
        "js_dns_promises_resolver_resolve_ptr"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveSoa",
        "js_dns_promises_resolver_resolve_soa"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveSrv",
        "js_dns_promises_resolver_resolve_srv"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveTlsa",
        "js_dns_promises_resolver_resolve_tlsa"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "resolveTxt",
        "js_dns_promises_resolver_resolve_txt"
    ),
    dns_resolver_record_sig!(
        "dns/promises",
        "reverse",
        "js_dns_promises_resolver_reverse"
    ),
    NativeModSig {
        module: "dns/promises",
        has_receiver: true,
        method: "cancel",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: true,
        method: "getServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: true,
        method: "setServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_set_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: true,
        method: "setLocalAddress",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
];
